// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/core.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/alecsavvy/clockwise/api/api/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// CoreServiceName is the fully-qualified name of the CoreService service.
	CoreServiceName = "api.v1.CoreService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// CoreServicePingProcedure is the fully-qualified name of the CoreService's Ping RPC.
	CoreServicePingProcedure = "/api.v1.CoreService/Ping"
	// CoreServiceSendTransactionProcedure is the fully-qualified name of the CoreService's
	// SendTransaction RPC.
	CoreServiceSendTransactionProcedure = "/api.v1.CoreService/SendTransaction"
	// CoreServiceGetTransactionProcedure is the fully-qualified name of the CoreService's
	// GetTransaction RPC.
	CoreServiceGetTransactionProcedure = "/api.v1.CoreService/GetTransaction"
	// CoreServiceGetBlockProcedure is the fully-qualified name of the CoreService's GetBlock RPC.
	CoreServiceGetBlockProcedure = "/api.v1.CoreService/GetBlock"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	coreServiceServiceDescriptor               = v1.File_api_v1_core_proto.Services().ByName("CoreService")
	coreServicePingMethodDescriptor            = coreServiceServiceDescriptor.Methods().ByName("Ping")
	coreServiceSendTransactionMethodDescriptor = coreServiceServiceDescriptor.Methods().ByName("SendTransaction")
	coreServiceGetTransactionMethodDescriptor  = coreServiceServiceDescriptor.Methods().ByName("GetTransaction")
	coreServiceGetBlockMethodDescriptor        = coreServiceServiceDescriptor.Methods().ByName("GetBlock")
)

// CoreServiceClient is a client for the api.v1.CoreService service.
type CoreServiceClient interface {
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	SendTransaction(context.Context, *connect.Request[v1.SendTransactionRequest]) (*connect.Response[v1.SendTransactionResponse], error)
	GetTransaction(context.Context, *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.GetTransactionResponse], error)
	GetBlock(context.Context, *connect.Request[v1.GetBlockRequest]) (*connect.Response[v1.GetBlockResponse], error)
}

// NewCoreServiceClient constructs a client for the api.v1.CoreService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewCoreServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) CoreServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &coreServiceClient{
		ping: connect.NewClient[v1.PingRequest, v1.PingResponse](
			httpClient,
			baseURL+CoreServicePingProcedure,
			connect.WithSchema(coreServicePingMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		sendTransaction: connect.NewClient[v1.SendTransactionRequest, v1.SendTransactionResponse](
			httpClient,
			baseURL+CoreServiceSendTransactionProcedure,
			connect.WithSchema(coreServiceSendTransactionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getTransaction: connect.NewClient[v1.GetTransactionRequest, v1.GetTransactionResponse](
			httpClient,
			baseURL+CoreServiceGetTransactionProcedure,
			connect.WithSchema(coreServiceGetTransactionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getBlock: connect.NewClient[v1.GetBlockRequest, v1.GetBlockResponse](
			httpClient,
			baseURL+CoreServiceGetBlockProcedure,
			connect.WithSchema(coreServiceGetBlockMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// coreServiceClient implements CoreServiceClient.
type coreServiceClient struct {
	ping            *connect.Client[v1.PingRequest, v1.PingResponse]
	sendTransaction *connect.Client[v1.SendTransactionRequest, v1.SendTransactionResponse]
	getTransaction  *connect.Client[v1.GetTransactionRequest, v1.GetTransactionResponse]
	getBlock        *connect.Client[v1.GetBlockRequest, v1.GetBlockResponse]
}

// Ping calls api.v1.CoreService.Ping.
func (c *coreServiceClient) Ping(ctx context.Context, req *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return c.ping.CallUnary(ctx, req)
}

// SendTransaction calls api.v1.CoreService.SendTransaction.
func (c *coreServiceClient) SendTransaction(ctx context.Context, req *connect.Request[v1.SendTransactionRequest]) (*connect.Response[v1.SendTransactionResponse], error) {
	return c.sendTransaction.CallUnary(ctx, req)
}

// GetTransaction calls api.v1.CoreService.GetTransaction.
func (c *coreServiceClient) GetTransaction(ctx context.Context, req *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.GetTransactionResponse], error) {
	return c.getTransaction.CallUnary(ctx, req)
}

// GetBlock calls api.v1.CoreService.GetBlock.
func (c *coreServiceClient) GetBlock(ctx context.Context, req *connect.Request[v1.GetBlockRequest]) (*connect.Response[v1.GetBlockResponse], error) {
	return c.getBlock.CallUnary(ctx, req)
}

// CoreServiceHandler is an implementation of the api.v1.CoreService service.
type CoreServiceHandler interface {
	Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error)
	SendTransaction(context.Context, *connect.Request[v1.SendTransactionRequest]) (*connect.Response[v1.SendTransactionResponse], error)
	GetTransaction(context.Context, *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.GetTransactionResponse], error)
	GetBlock(context.Context, *connect.Request[v1.GetBlockRequest]) (*connect.Response[v1.GetBlockResponse], error)
}

// NewCoreServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewCoreServiceHandler(svc CoreServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	coreServicePingHandler := connect.NewUnaryHandler(
		CoreServicePingProcedure,
		svc.Ping,
		connect.WithSchema(coreServicePingMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	coreServiceSendTransactionHandler := connect.NewUnaryHandler(
		CoreServiceSendTransactionProcedure,
		svc.SendTransaction,
		connect.WithSchema(coreServiceSendTransactionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	coreServiceGetTransactionHandler := connect.NewUnaryHandler(
		CoreServiceGetTransactionProcedure,
		svc.GetTransaction,
		connect.WithSchema(coreServiceGetTransactionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	coreServiceGetBlockHandler := connect.NewUnaryHandler(
		CoreServiceGetBlockProcedure,
		svc.GetBlock,
		connect.WithSchema(coreServiceGetBlockMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/api.v1.CoreService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case CoreServicePingProcedure:
			coreServicePingHandler.ServeHTTP(w, r)
		case CoreServiceSendTransactionProcedure:
			coreServiceSendTransactionHandler.ServeHTTP(w, r)
		case CoreServiceGetTransactionProcedure:
			coreServiceGetTransactionHandler.ServeHTTP(w, r)
		case CoreServiceGetBlockProcedure:
			coreServiceGetBlockHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedCoreServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedCoreServiceHandler struct{}

func (UnimplementedCoreServiceHandler) Ping(context.Context, *connect.Request[v1.PingRequest]) (*connect.Response[v1.PingResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.CoreService.Ping is not implemented"))
}

func (UnimplementedCoreServiceHandler) SendTransaction(context.Context, *connect.Request[v1.SendTransactionRequest]) (*connect.Response[v1.SendTransactionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.CoreService.SendTransaction is not implemented"))
}

func (UnimplementedCoreServiceHandler) GetTransaction(context.Context, *connect.Request[v1.GetTransactionRequest]) (*connect.Response[v1.GetTransactionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.CoreService.GetTransaction is not implemented"))
}

func (UnimplementedCoreServiceHandler) GetBlock(context.Context, *connect.Request[v1.GetBlockRequest]) (*connect.Response[v1.GetBlockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("api.v1.CoreService.GetBlock is not implemented"))
}
