// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: api/v1/ddex.proto

package apiv1connect

import (
	connect "connectrpc.com/connect"
	v1 "github.com/alecsavvy/clockwise/api/api/v1"
	http "net/http"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DDEXServiceName is the fully-qualified name of the DDEXService service.
	DDEXServiceName = "api.v1.DDEXService"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	dDEXServiceServiceDescriptor = v1.File_api_v1_ddex_proto.Services().ByName("DDEXService")
)

// DDEXServiceClient is a client for the api.v1.DDEXService service.
type DDEXServiceClient interface {
}

// NewDDEXServiceClient constructs a client for the api.v1.DDEXService service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDDEXServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DDEXServiceClient {
	return &dDEXServiceClient{}
}

// dDEXServiceClient implements DDEXServiceClient.
type dDEXServiceClient struct {
}

// DDEXServiceHandler is an implementation of the api.v1.DDEXService service.
type DDEXServiceHandler interface {
}

// NewDDEXServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDDEXServiceHandler(svc DDEXServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	return "/api.v1.DDEXService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDDEXServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDDEXServiceHandler struct{}
