// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Kv struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type Mutation struct {
}

type NewKv struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type NewTrack struct {
	Title       string `json:"title"`
	StreamURL   string `json:"streamUrl"`
	Description string `json:"description"`
	UserID      string `json:"userId"`
}

type NewUser struct {
	Handle string `json:"handle"`
	Bio    string `json:"bio"`
}

type Query struct {
}

type Track struct {
	ID          string `json:"id"`
	Title       string `json:"title"`
	StreamURL   string `json:"streamUrl"`
	Description string `json:"description"`
	UserID      string `json:"userId"`
}

type User struct {
	ID     string `json:"id"`
	Handle string `json:"handle"`
	Bio    string `json:"bio"`
}
