log_level = "main:info,state:warn,statesync:warn,*:error"

[rpc]
laddr = "tcp://0.0.0.0:26657"

[p2p]
laddr = "tcp://0.0.0.0:26656"

[mempool]
size = 10000
max_tx_bytes = 1024
max_txs_bytes = 1073741824

[instrumentation]
prometheus = false

[consensus]
create_empty_blocks = false
create_empty_blocks_interval = "0s"
timeout_commit = "1s"

[storage.pruning.data_companion]
enabled = true

[grpc.privileged]
laddr = "tcp://0.0.0.0:26660"

[grpc.privileged.pruning_service]
enabled = true

