log_level = "main:info,state:warn,statesync:warn,*:error"
proxy_app = ""

[rpc]
laddr = "tcp://0.0.0.0:26657"

[p2p]
laddr = "tcp://0.0.0.0:26656"

[mempool]
# 10 gigs total for mempool
size = 10240
max_tx_bytes = 1048576
max_txs_bytes = 10737418240

[instrumentation]
prometheus = false

[consensus]
create_empty_blocks = false
create_empty_blocks_interval = "0s"
timeout_commit = "1s"
