log_level = "main:info,state:warn,statesync:warn,*:error"

[rpc]
laddr = "tcp://0.0.0.0:26657"

[p2p]
laddr = "tcp://0.0.0.0:26656"

[instrumentation]
prometheus = false

[consensus]
create_empty_blocks = false
create_empty_blocks_interval = "0s"

[pruning]
strategy = "custom"
pruning_keep_recent = "50"
pruning_keep_every = "0"
pruning_interval = "10"
