log_level = "main:info,state:info,statesync:info,*:error"

[rpc]
laddr = "tcp://0.0.0.0:26657"

[p2p]
laddr = "tcp://0.0.0.0:26656"

[instrumentation]
prometheus = false

[consensus]
create_empty_blocks = false
create_empty_blocks_interval = "0s"
