services:
  node-0:
    container_name: discoveryprovider0.docker.co
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
      target: final
      args:
        NODE: "0"
    environment:
      - pgConnectionString=postgresql://postgres:pass@discovery_db:5432/db0?sslmode=disable
    restart: unless-stopped
    ports:
      - "6600:26656" # CometBFT P2P Server
      - "6601:26657" # CometBFT RPC Server
      - "6603:26659" # Clockwise GQL Server
    networks:
      audius-testnet:
        ipv4_address: 192.167.10.2
    depends_on:
      - geth
      - postgres

  node-1:
    container_name: discoveryprovider1.docker.co
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
      target: final
      args:
        NODE: "1"
    environment:
      - pgConnectionString=postgresql://postgres:pass@discovery_db:5432/db1?sslmode=disable
    restart: unless-stopped
    ports:
      - "6610:26656"
      - "6611:26657"
      - "6613:26659"
    networks:
      audius-testnet:
        ipv4_address: 192.167.10.3
    depends_on:
      - geth
      - postgres

  node-2:
    container_name: discoveryprovider2.docker.co
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
      target: final
      args:
        NODE: "2"
    environment:
      - pgConnectionString=postgresql://postgres:pass@discovery_db:5432/db2?sslmode=disable
    restart: unless-stopped
    ports:
      - "6620:26656"
      - "6621:26657"
      - "6623:26659"
    networks:
      audius-testnet:
        ipv4_address: 192.167.10.4
    depends_on:
      - geth
      - postgres

  node-3:
    container_name: discoveryprovider3.docker.co
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
      target: final
      args:
        NODE: "3"
    environment:
      - pgConnectionString=postgresql://postgres:pass@discovery_db:5432/db3?sslmode=disable
    restart: unless-stopped
    ports:
      - "6630:26656"
      - "6631:26657"
      - "6633:26659"
    networks:
      audius-testnet:
        ipv4_address: 192.167.10.5
    depends_on:
      - geth
      - postgres

  node-4:
    container_name: discoveryprovider4.docker.co
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
      target: final
      args:
        NODE: "4"
    environment:
      - pgConnectionString=postgresql://postgres:pass@discovery_db:5432/db4?sslmode=disable
    restart: unless-stopped
    ports:
      - "6640:26656"
      - "6641:26657"
      - "6643:26659"
    networks:
      audius-testnet:
        ipv4_address: 192.167.10.6
    depends_on:
      - geth
      - postgres

  node-5:
    container_name: discoveryprovider5.docker.co
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
      target: final
      args:
        NODE: "5"
    environment:
      - pgConnectionString=postgresql://postgres:pass@discovery_db:5432/db5?sslmode=disable
    restart: unless-stopped
    ports:
      - "6650:26656"
      - "6651:26657"
      - "6653:26659"
    networks:
      audius-testnet:
        ipv4_address: 192.167.10.7
    depends_on:
      - geth
      - postgres

  node-6:
    container_name: discoveryprovider6.docker.co
    build:
      context: ../
      dockerfile: ./infra/Dockerfile
      target: final
      args:
        NODE: "6"
    environment:
      - pgConnectionString=postgresql://postgres:pass@discovery_db:5432/db6?sslmode=disable
    restart: unless-stopped
    ports:
      - "6660:26656"
      - "6661:26657"
      - "6663:26659"
    networks:
      audius-testnet:
        ipv4_address: 192.167.10.8
    depends_on:
      - geth
      - postgres

  loadtest:
    container_name: moshpit
    build:
      context: ../
      dockerfile: ./infra/Dockerfile.loadtest
      target: final
    restart: unless-stopped
    networks:
      - audius-testnet
    ports:
      - "8080:8080"
    depends_on:
      - node-0
      - node-1
      - node-2
      - node-3
      - node-4
      - node-5
      - node-6

  geth:
    container_name: ethereum.docker.co
    image: ethereum/client-go:latest
    command:
      - "--dev"
      - "--http"
      - "--http.addr"
      - "0.0.0.0"
      - "--http.api"
      - "personal,eth,net,web3,txpool,miner"
      - "--verbosity"
      - "3"
    ports:
      - "8545:8545"
      - "8546:8546"
    networks:
      audius-testnet:
        ipv4_address: 192.167.10.9

  postgres:
    image: postgres:15
    container_name: discovery_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: main_db
    ports:
      - "5432:5432"
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d
    networks:
      audius-testnet:
        ipv4_address: 192.167.10.10

networks:
  audius-testnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.167.0.0/16
