// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: api/v1/ddex.proto

package apiv1

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

// DDEXServiceClient is the client API for DDEXService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DDEXServiceClient interface {
}

type dDEXServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDDEXServiceClient(cc grpc.ClientConnInterface) DDEXServiceClient {
	return &dDEXServiceClient{cc}
}

// DDEXServiceServer is the server API for DDEXService service.
// All implementations must embed UnimplementedDDEXServiceServer
// for forward compatibility.
type DDEXServiceServer interface {
	mustEmbedUnimplementedDDEXServiceServer()
}

// UnimplementedDDEXServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDDEXServiceServer struct{}

func (UnimplementedDDEXServiceServer) mustEmbedUnimplementedDDEXServiceServer() {}
func (UnimplementedDDEXServiceServer) testEmbeddedByValue()                     {}

// UnsafeDDEXServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DDEXServiceServer will
// result in compilation errors.
type UnsafeDDEXServiceServer interface {
	mustEmbedUnimplementedDDEXServiceServer()
}

func RegisterDDEXServiceServer(s grpc.ServiceRegistrar, srv DDEXServiceServer) {
	// If the following call pancis, it indicates UnimplementedDDEXServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DDEXService_ServiceDesc, srv)
}

// DDEXService_ServiceDesc is the grpc.ServiceDesc for DDEXService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DDEXService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.DDEXService",
	HandlerType: (*DDEXServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "api/v1/ddex.proto",
}
