// Code generated by generate-go-extensions. DO NOT EDIT.

package ernv381

import "strings"

// XMLString returns the XML string representation of DdexCCurrentTerritoryCode
func (e DdexCCurrentTerritoryCode) XMLString() string {
	switch e {
	default:
		return ""
	}
}

// ParseDdexCCurrentTerritoryCodeString parses a string value to DdexCCurrentTerritoryCode enum (case-insensitive)
func ParseDdexCCurrentTerritoryCodeString(s string) (DdexCCurrentTerritoryCode, bool) {
	s = strings.ToUpper(s)
	switch s {
	default:
		return DdexCCurrentTerritoryCode(0), false
	}
}

