// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cometbft/rpc/grpc/v1beta1/types.proto

package grpcv1beta1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1beta1 "github.com/alecsavvy/clockwise/api/cometbft/rpc/grpc/v1beta1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BroadcastAPIName is the fully-qualified name of the BroadcastAPI service.
	BroadcastAPIName = "cometbft.rpc.grpc.v1beta1.BroadcastAPI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BroadcastAPIPingProcedure is the fully-qualified name of the BroadcastAPI's Ping RPC.
	BroadcastAPIPingProcedure = "/cometbft.rpc.grpc.v1beta1.BroadcastAPI/Ping"
	// BroadcastAPIBroadcastTxProcedure is the fully-qualified name of the BroadcastAPI's BroadcastTx
	// RPC.
	BroadcastAPIBroadcastTxProcedure = "/cometbft.rpc.grpc.v1beta1.BroadcastAPI/BroadcastTx"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	broadcastAPIServiceDescriptor           = v1beta1.File_cometbft_rpc_grpc_v1beta1_types_proto.Services().ByName("BroadcastAPI")
	broadcastAPIPingMethodDescriptor        = broadcastAPIServiceDescriptor.Methods().ByName("Ping")
	broadcastAPIBroadcastTxMethodDescriptor = broadcastAPIServiceDescriptor.Methods().ByName("BroadcastTx")
)

// BroadcastAPIClient is a client for the cometbft.rpc.grpc.v1beta1.BroadcastAPI service.
type BroadcastAPIClient interface {
	// Ping the connection.
	Ping(context.Context, *connect.Request[v1beta1.RequestPing]) (*connect.Response[v1beta1.ResponsePing], error)
	// BroadcastTx broadcasts the transaction.
	BroadcastTx(context.Context, *connect.Request[v1beta1.RequestBroadcastTx]) (*connect.Response[v1beta1.ResponseBroadcastTx], error)
}

// NewBroadcastAPIClient constructs a client for the cometbft.rpc.grpc.v1beta1.BroadcastAPI service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBroadcastAPIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BroadcastAPIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &broadcastAPIClient{
		ping: connect.NewClient[v1beta1.RequestPing, v1beta1.ResponsePing](
			httpClient,
			baseURL+BroadcastAPIPingProcedure,
			connect.WithSchema(broadcastAPIPingMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		broadcastTx: connect.NewClient[v1beta1.RequestBroadcastTx, v1beta1.ResponseBroadcastTx](
			httpClient,
			baseURL+BroadcastAPIBroadcastTxProcedure,
			connect.WithSchema(broadcastAPIBroadcastTxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// broadcastAPIClient implements BroadcastAPIClient.
type broadcastAPIClient struct {
	ping        *connect.Client[v1beta1.RequestPing, v1beta1.ResponsePing]
	broadcastTx *connect.Client[v1beta1.RequestBroadcastTx, v1beta1.ResponseBroadcastTx]
}

// Ping calls cometbft.rpc.grpc.v1beta1.BroadcastAPI.Ping.
func (c *broadcastAPIClient) Ping(ctx context.Context, req *connect.Request[v1beta1.RequestPing]) (*connect.Response[v1beta1.ResponsePing], error) {
	return c.ping.CallUnary(ctx, req)
}

// BroadcastTx calls cometbft.rpc.grpc.v1beta1.BroadcastAPI.BroadcastTx.
func (c *broadcastAPIClient) BroadcastTx(ctx context.Context, req *connect.Request[v1beta1.RequestBroadcastTx]) (*connect.Response[v1beta1.ResponseBroadcastTx], error) {
	return c.broadcastTx.CallUnary(ctx, req)
}

// BroadcastAPIHandler is an implementation of the cometbft.rpc.grpc.v1beta1.BroadcastAPI service.
type BroadcastAPIHandler interface {
	// Ping the connection.
	Ping(context.Context, *connect.Request[v1beta1.RequestPing]) (*connect.Response[v1beta1.ResponsePing], error)
	// BroadcastTx broadcasts the transaction.
	BroadcastTx(context.Context, *connect.Request[v1beta1.RequestBroadcastTx]) (*connect.Response[v1beta1.ResponseBroadcastTx], error)
}

// NewBroadcastAPIHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBroadcastAPIHandler(svc BroadcastAPIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	broadcastAPIPingHandler := connect.NewUnaryHandler(
		BroadcastAPIPingProcedure,
		svc.Ping,
		connect.WithSchema(broadcastAPIPingMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	broadcastAPIBroadcastTxHandler := connect.NewUnaryHandler(
		BroadcastAPIBroadcastTxProcedure,
		svc.BroadcastTx,
		connect.WithSchema(broadcastAPIBroadcastTxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/cometbft.rpc.grpc.v1beta1.BroadcastAPI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BroadcastAPIPingProcedure:
			broadcastAPIPingHandler.ServeHTTP(w, r)
		case BroadcastAPIBroadcastTxProcedure:
			broadcastAPIBroadcastTxHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBroadcastAPIHandler returns CodeUnimplemented from all methods.
type UnimplementedBroadcastAPIHandler struct{}

func (UnimplementedBroadcastAPIHandler) Ping(context.Context, *connect.Request[v1beta1.RequestPing]) (*connect.Response[v1beta1.ResponsePing], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.rpc.grpc.v1beta1.BroadcastAPI.Ping is not implemented"))
}

func (UnimplementedBroadcastAPIHandler) BroadcastTx(context.Context, *connect.Request[v1beta1.RequestBroadcastTx]) (*connect.Response[v1beta1.ResponseBroadcastTx], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.rpc.grpc.v1beta1.BroadcastAPI.BroadcastTx is not implemented"))
}
