// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Follow struct {
	FollowerID string `json:"followerId"`
	FolloweeID string `json:"followeeId"`
}

type Mutation struct {
}

type NewFollow struct {
	FollowerID string `json:"followerId"`
	FolloweeID string `json:"followeeId"`
}

type NewRepost struct {
	ReposterID string `json:"reposterId"`
	TrackID    string `json:"trackId"`
}

type NewTrack struct {
	Title       string `json:"title"`
	StreamURL   string `json:"streamUrl"`
	Description string `json:"description"`
	UserID      string `json:"userId"`
}

type NewUnfollow struct {
	FollowerID string `json:"followerId"`
	FolloweeID string `json:"followeeId"`
}

type NewUnrepost struct {
	ReposterID string `json:"reposterId"`
	TrackID    string `json:"trackId"`
}

type NewUser struct {
	Address string `json:"address"`
	Handle  string `json:"handle"`
	Bio     string `json:"bio"`
}

type Query struct {
}

type Repost struct {
	ReposterID string `json:"reposterId"`
	TrackID    string `json:"trackId"`
}

type Subscription struct {
}

type Track struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	StreamURL   string    `json:"streamUrl"`
	Description string    `json:"description"`
	UserID      string    `json:"userId"`
	Reposts     []*Repost `json:"reposts"`
}

type User struct {
	Handle    string    `json:"handle"`
	Address   string    `json:"address"`
	Bio       string    `json:"bio"`
	Followers []*Follow `json:"followers"`
	Following []*Follow `json:"following"`
	Reposts   []*Repost `json:"reposts"`
	Tracks    []*Track  `json:"tracks"`
}
