// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Follow struct {
	FollowerID  string
	FollowingID string
}

type Repost struct {
	ReposterID string
	TrackID    string
}

type Track struct {
	ID          string
	Title       string
	StreamUrl   string
	Description string
	UserID      string
}

type User struct {
	ID      string
	Handle  string
	Address string
	Bio     string
}
