// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

type Block struct {
	Blocknumber int64
	Blockhash   []byte
}

type Follow struct {
	ID          string
	FollowerID  string
	FollowingID string
	CreatedAt   int64
}

type Repost struct {
	ID         string
	ReposterID string
	TrackID    string
	CreatedAt  int64
}

type Track struct {
	ID          string
	Title       string
	StreamUrl   string
	Description string
	Genre       string
	UserID      string
	CreatedAt   int64
}

type User struct {
	ID        string
	Handle    string
	Address   string
	Bio       string
	CreatedAt int64
}
