// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import ()

type Block struct {
	ID          string
	Blocknumber int32
	Blockhash   string
}

type Follow struct {
	ID          string
	FollowerID  string
	FollowingID string
	CreatedAt   int32
}

type Repost struct {
	ID         string
	ReposterID string
	TrackID    string
	CreatedAt  int32
}

type Track struct {
	ID          string
	Title       string
	StreamUrl   string
	Description string
	Genre       string
	UserID      string
	CreatedAt   int32
}

type User struct {
	ID        string
	Handle    string
	Address   string
	Bio       string
	CreatedAt int32
}
