mutation users {
  maxine: createUser(
    input: { handle: "maxine", address: "0x1985", bio: "a movie star" }
  ) {
    handle
    address
    bio
    txhash
  }
  pearl: createUser(
    input: { handle: "pearl", address: "0x1918", bio: "a wannabe movie star" }
  ) {
    handle
    address
    bio
    txhash
  }
  teddy: createUser(
    input: { handle: "teddy", address: "0x1973", bio: "maxine's agent" }
  ) {
    handle
    address
    bio
    txhash
  }
}

mutation tracks {
  maxineTheme: createTrack(
    input: {
      title: "maxine's theme"
      streamUrl: "contentnode/file.mp3"
      userId: "0x1985"
      description: "a powerful anthemic song"
    }
  ) {
    id
    title
    description
    streamUrl
    userId
  }
  pearlTheme: createTrack(
    input: {
      title: "pearl's theme"
      streamUrl: "contentnode/file_2.mp3"
      userId: "0x1918"
      description: "a somber orchestral track"
    }
  ) {
    id
    title
    description
    streamUrl
    userId
  }
}

mutation action {
  teddyRepostOne: repostTrack(
    input: {
      trackId: "ae4dea03-eef2-4999-bb69-e237cf8a595e"
      reposterId: "0x1973"
    }
  ) {
    trackId
    reposterId
  }
  teddyRepostTwo: repostTrack(
    input: {
      trackId: "08671323-efe7-4f7c-adc2-d055c31b0cb7"
      reposterId: "0x1973"
    }
  ) {
    trackId
    reposterId
  }
  teddyFollowMaxine: followUser(
    input: { followerId: "0x1973", followeeId: "0x1985" }
  ) {
    followerId
    followeeId
  }
  pearlFollowMaxine: followUser(
    input: { followerId: "0x1918", followeeId: "0x1985" }
  ) {
    followerId
    followeeId
  }
}

query getusers {
  maxine: getUser(input: { address: "0x1985" }) {
    handle
    address
    bio
    tracks {
      title
      userId
      streamUrl
    }
    followers {
      followerId
    }
    following {
      followeeId
    }
    reposts {
      trackId
    }
  }
  pearl: getUser(input: { address: "0x1918" }) {
    handle
    address
    bio
    tracks {
      title
      userId
      streamUrl
    }
    followers {
      followerId
    }
    following {
      followeeId
    }
    reposts {
      trackId
    }
  }
  teddy: getUser(input: { address: "0x1973" }) {
    handle
    address
    bio
    tracks {
      title
      userId
      streamUrl
    }
    followers {
      followerId
    }
    following {
      followeeId
    }
    reposts {
      trackId
    }
  }
}

subscription subs {
  entityUpdates {
    ... on User {
      address
      handle
      bio
    }
    ... on Track {
      title
      description
      streamUrl
    }
    ... on Repost {
      reposterId
      trackId
    }
    ... on Follow {
      followerId
      followeeId
    }
  }
}
