// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Block struct {
	Blocknumber int64
	Blocktime   pgtype.Date
}

type Track struct {
	ID          pgtype.UUID
	Title       string
	StreamUrl   string
	Description pgtype.Text
	UserID      pgtype.UUID
}

type User struct {
	ID     pgtype.UUID
	Handle string
	Bio    pgtype.Text
}
