// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cometbft/abci/v1/service.proto

package abciv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/alecsavvy/clockwise/api/cometbft/abci/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ABCIServiceName is the fully-qualified name of the ABCIService service.
	ABCIServiceName = "cometbft.abci.v1.ABCIService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ABCIServiceEchoProcedure is the fully-qualified name of the ABCIService's Echo RPC.
	ABCIServiceEchoProcedure = "/cometbft.abci.v1.ABCIService/Echo"
	// ABCIServiceFlushProcedure is the fully-qualified name of the ABCIService's Flush RPC.
	ABCIServiceFlushProcedure = "/cometbft.abci.v1.ABCIService/Flush"
	// ABCIServiceInfoProcedure is the fully-qualified name of the ABCIService's Info RPC.
	ABCIServiceInfoProcedure = "/cometbft.abci.v1.ABCIService/Info"
	// ABCIServiceCheckTxProcedure is the fully-qualified name of the ABCIService's CheckTx RPC.
	ABCIServiceCheckTxProcedure = "/cometbft.abci.v1.ABCIService/CheckTx"
	// ABCIServiceQueryProcedure is the fully-qualified name of the ABCIService's Query RPC.
	ABCIServiceQueryProcedure = "/cometbft.abci.v1.ABCIService/Query"
	// ABCIServiceCommitProcedure is the fully-qualified name of the ABCIService's Commit RPC.
	ABCIServiceCommitProcedure = "/cometbft.abci.v1.ABCIService/Commit"
	// ABCIServiceInitChainProcedure is the fully-qualified name of the ABCIService's InitChain RPC.
	ABCIServiceInitChainProcedure = "/cometbft.abci.v1.ABCIService/InitChain"
	// ABCIServiceListSnapshotsProcedure is the fully-qualified name of the ABCIService's ListSnapshots
	// RPC.
	ABCIServiceListSnapshotsProcedure = "/cometbft.abci.v1.ABCIService/ListSnapshots"
	// ABCIServiceOfferSnapshotProcedure is the fully-qualified name of the ABCIService's OfferSnapshot
	// RPC.
	ABCIServiceOfferSnapshotProcedure = "/cometbft.abci.v1.ABCIService/OfferSnapshot"
	// ABCIServiceLoadSnapshotChunkProcedure is the fully-qualified name of the ABCIService's
	// LoadSnapshotChunk RPC.
	ABCIServiceLoadSnapshotChunkProcedure = "/cometbft.abci.v1.ABCIService/LoadSnapshotChunk"
	// ABCIServiceApplySnapshotChunkProcedure is the fully-qualified name of the ABCIService's
	// ApplySnapshotChunk RPC.
	ABCIServiceApplySnapshotChunkProcedure = "/cometbft.abci.v1.ABCIService/ApplySnapshotChunk"
	// ABCIServicePrepareProposalProcedure is the fully-qualified name of the ABCIService's
	// PrepareProposal RPC.
	ABCIServicePrepareProposalProcedure = "/cometbft.abci.v1.ABCIService/PrepareProposal"
	// ABCIServiceProcessProposalProcedure is the fully-qualified name of the ABCIService's
	// ProcessProposal RPC.
	ABCIServiceProcessProposalProcedure = "/cometbft.abci.v1.ABCIService/ProcessProposal"
	// ABCIServiceExtendVoteProcedure is the fully-qualified name of the ABCIService's ExtendVote RPC.
	ABCIServiceExtendVoteProcedure = "/cometbft.abci.v1.ABCIService/ExtendVote"
	// ABCIServiceVerifyVoteExtensionProcedure is the fully-qualified name of the ABCIService's
	// VerifyVoteExtension RPC.
	ABCIServiceVerifyVoteExtensionProcedure = "/cometbft.abci.v1.ABCIService/VerifyVoteExtension"
	// ABCIServiceFinalizeBlockProcedure is the fully-qualified name of the ABCIService's FinalizeBlock
	// RPC.
	ABCIServiceFinalizeBlockProcedure = "/cometbft.abci.v1.ABCIService/FinalizeBlock"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	aBCIServiceServiceDescriptor                   = v1.File_cometbft_abci_v1_service_proto.Services().ByName("ABCIService")
	aBCIServiceEchoMethodDescriptor                = aBCIServiceServiceDescriptor.Methods().ByName("Echo")
	aBCIServiceFlushMethodDescriptor               = aBCIServiceServiceDescriptor.Methods().ByName("Flush")
	aBCIServiceInfoMethodDescriptor                = aBCIServiceServiceDescriptor.Methods().ByName("Info")
	aBCIServiceCheckTxMethodDescriptor             = aBCIServiceServiceDescriptor.Methods().ByName("CheckTx")
	aBCIServiceQueryMethodDescriptor               = aBCIServiceServiceDescriptor.Methods().ByName("Query")
	aBCIServiceCommitMethodDescriptor              = aBCIServiceServiceDescriptor.Methods().ByName("Commit")
	aBCIServiceInitChainMethodDescriptor           = aBCIServiceServiceDescriptor.Methods().ByName("InitChain")
	aBCIServiceListSnapshotsMethodDescriptor       = aBCIServiceServiceDescriptor.Methods().ByName("ListSnapshots")
	aBCIServiceOfferSnapshotMethodDescriptor       = aBCIServiceServiceDescriptor.Methods().ByName("OfferSnapshot")
	aBCIServiceLoadSnapshotChunkMethodDescriptor   = aBCIServiceServiceDescriptor.Methods().ByName("LoadSnapshotChunk")
	aBCIServiceApplySnapshotChunkMethodDescriptor  = aBCIServiceServiceDescriptor.Methods().ByName("ApplySnapshotChunk")
	aBCIServicePrepareProposalMethodDescriptor     = aBCIServiceServiceDescriptor.Methods().ByName("PrepareProposal")
	aBCIServiceProcessProposalMethodDescriptor     = aBCIServiceServiceDescriptor.Methods().ByName("ProcessProposal")
	aBCIServiceExtendVoteMethodDescriptor          = aBCIServiceServiceDescriptor.Methods().ByName("ExtendVote")
	aBCIServiceVerifyVoteExtensionMethodDescriptor = aBCIServiceServiceDescriptor.Methods().ByName("VerifyVoteExtension")
	aBCIServiceFinalizeBlockMethodDescriptor       = aBCIServiceServiceDescriptor.Methods().ByName("FinalizeBlock")
)

// ABCIServiceClient is a client for the cometbft.abci.v1.ABCIService service.
type ABCIServiceClient interface {
	// Echo returns back the same message it is sent.
	Echo(context.Context, *connect.Request[v1.EchoRequest]) (*connect.Response[v1.EchoResponse], error)
	// Flush flushes the write buffer.
	Flush(context.Context, *connect.Request[v1.FlushRequest]) (*connect.Response[v1.FlushResponse], error)
	// Info returns information about the application state.
	Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error)
	// CheckTx validates a transaction.
	CheckTx(context.Context, *connect.Request[v1.CheckTxRequest]) (*connect.Response[v1.CheckTxResponse], error)
	// Query queries the application state.
	Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResponse], error)
	// Commit commits a block of transactions.
	Commit(context.Context, *connect.Request[v1.CommitRequest]) (*connect.Response[v1.CommitResponse], error)
	// InitChain initializes the blockchain.
	InitChain(context.Context, *connect.Request[v1.InitChainRequest]) (*connect.Response[v1.InitChainResponse], error)
	// ListSnapshots lists all the available snapshots.
	ListSnapshots(context.Context, *connect.Request[v1.ListSnapshotsRequest]) (*connect.Response[v1.ListSnapshotsResponse], error)
	// OfferSnapshot sends a snapshot offer.
	OfferSnapshot(context.Context, *connect.Request[v1.OfferSnapshotRequest]) (*connect.Response[v1.OfferSnapshotResponse], error)
	// LoadSnapshotChunk returns a chunk of snapshot.
	LoadSnapshotChunk(context.Context, *connect.Request[v1.LoadSnapshotChunkRequest]) (*connect.Response[v1.LoadSnapshotChunkResponse], error)
	// ApplySnapshotChunk applies a chunk of snapshot.
	ApplySnapshotChunk(context.Context, *connect.Request[v1.ApplySnapshotChunkRequest]) (*connect.Response[v1.ApplySnapshotChunkResponse], error)
	// PrepareProposal returns a proposal for the next block.
	PrepareProposal(context.Context, *connect.Request[v1.PrepareProposalRequest]) (*connect.Response[v1.PrepareProposalResponse], error)
	// ProcessProposal validates a proposal.
	ProcessProposal(context.Context, *connect.Request[v1.ProcessProposalRequest]) (*connect.Response[v1.ProcessProposalResponse], error)
	// ExtendVote extends a vote with application-injected data (vote extensions).
	ExtendVote(context.Context, *connect.Request[v1.ExtendVoteRequest]) (*connect.Response[v1.ExtendVoteResponse], error)
	// VerifyVoteExtension verifies a vote extension.
	VerifyVoteExtension(context.Context, *connect.Request[v1.VerifyVoteExtensionRequest]) (*connect.Response[v1.VerifyVoteExtensionResponse], error)
	// FinalizeBlock finalizes a block.
	FinalizeBlock(context.Context, *connect.Request[v1.FinalizeBlockRequest]) (*connect.Response[v1.FinalizeBlockResponse], error)
}

// NewABCIServiceClient constructs a client for the cometbft.abci.v1.ABCIService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewABCIServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ABCIServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &aBCIServiceClient{
		echo: connect.NewClient[v1.EchoRequest, v1.EchoResponse](
			httpClient,
			baseURL+ABCIServiceEchoProcedure,
			connect.WithSchema(aBCIServiceEchoMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		flush: connect.NewClient[v1.FlushRequest, v1.FlushResponse](
			httpClient,
			baseURL+ABCIServiceFlushProcedure,
			connect.WithSchema(aBCIServiceFlushMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		info: connect.NewClient[v1.InfoRequest, v1.InfoResponse](
			httpClient,
			baseURL+ABCIServiceInfoProcedure,
			connect.WithSchema(aBCIServiceInfoMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		checkTx: connect.NewClient[v1.CheckTxRequest, v1.CheckTxResponse](
			httpClient,
			baseURL+ABCIServiceCheckTxProcedure,
			connect.WithSchema(aBCIServiceCheckTxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		query: connect.NewClient[v1.QueryRequest, v1.QueryResponse](
			httpClient,
			baseURL+ABCIServiceQueryProcedure,
			connect.WithSchema(aBCIServiceQueryMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		commit: connect.NewClient[v1.CommitRequest, v1.CommitResponse](
			httpClient,
			baseURL+ABCIServiceCommitProcedure,
			connect.WithSchema(aBCIServiceCommitMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		initChain: connect.NewClient[v1.InitChainRequest, v1.InitChainResponse](
			httpClient,
			baseURL+ABCIServiceInitChainProcedure,
			connect.WithSchema(aBCIServiceInitChainMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listSnapshots: connect.NewClient[v1.ListSnapshotsRequest, v1.ListSnapshotsResponse](
			httpClient,
			baseURL+ABCIServiceListSnapshotsProcedure,
			connect.WithSchema(aBCIServiceListSnapshotsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		offerSnapshot: connect.NewClient[v1.OfferSnapshotRequest, v1.OfferSnapshotResponse](
			httpClient,
			baseURL+ABCIServiceOfferSnapshotProcedure,
			connect.WithSchema(aBCIServiceOfferSnapshotMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		loadSnapshotChunk: connect.NewClient[v1.LoadSnapshotChunkRequest, v1.LoadSnapshotChunkResponse](
			httpClient,
			baseURL+ABCIServiceLoadSnapshotChunkProcedure,
			connect.WithSchema(aBCIServiceLoadSnapshotChunkMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		applySnapshotChunk: connect.NewClient[v1.ApplySnapshotChunkRequest, v1.ApplySnapshotChunkResponse](
			httpClient,
			baseURL+ABCIServiceApplySnapshotChunkProcedure,
			connect.WithSchema(aBCIServiceApplySnapshotChunkMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		prepareProposal: connect.NewClient[v1.PrepareProposalRequest, v1.PrepareProposalResponse](
			httpClient,
			baseURL+ABCIServicePrepareProposalProcedure,
			connect.WithSchema(aBCIServicePrepareProposalMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		processProposal: connect.NewClient[v1.ProcessProposalRequest, v1.ProcessProposalResponse](
			httpClient,
			baseURL+ABCIServiceProcessProposalProcedure,
			connect.WithSchema(aBCIServiceProcessProposalMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		extendVote: connect.NewClient[v1.ExtendVoteRequest, v1.ExtendVoteResponse](
			httpClient,
			baseURL+ABCIServiceExtendVoteProcedure,
			connect.WithSchema(aBCIServiceExtendVoteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		verifyVoteExtension: connect.NewClient[v1.VerifyVoteExtensionRequest, v1.VerifyVoteExtensionResponse](
			httpClient,
			baseURL+ABCIServiceVerifyVoteExtensionProcedure,
			connect.WithSchema(aBCIServiceVerifyVoteExtensionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		finalizeBlock: connect.NewClient[v1.FinalizeBlockRequest, v1.FinalizeBlockResponse](
			httpClient,
			baseURL+ABCIServiceFinalizeBlockProcedure,
			connect.WithSchema(aBCIServiceFinalizeBlockMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// aBCIServiceClient implements ABCIServiceClient.
type aBCIServiceClient struct {
	echo                *connect.Client[v1.EchoRequest, v1.EchoResponse]
	flush               *connect.Client[v1.FlushRequest, v1.FlushResponse]
	info                *connect.Client[v1.InfoRequest, v1.InfoResponse]
	checkTx             *connect.Client[v1.CheckTxRequest, v1.CheckTxResponse]
	query               *connect.Client[v1.QueryRequest, v1.QueryResponse]
	commit              *connect.Client[v1.CommitRequest, v1.CommitResponse]
	initChain           *connect.Client[v1.InitChainRequest, v1.InitChainResponse]
	listSnapshots       *connect.Client[v1.ListSnapshotsRequest, v1.ListSnapshotsResponse]
	offerSnapshot       *connect.Client[v1.OfferSnapshotRequest, v1.OfferSnapshotResponse]
	loadSnapshotChunk   *connect.Client[v1.LoadSnapshotChunkRequest, v1.LoadSnapshotChunkResponse]
	applySnapshotChunk  *connect.Client[v1.ApplySnapshotChunkRequest, v1.ApplySnapshotChunkResponse]
	prepareProposal     *connect.Client[v1.PrepareProposalRequest, v1.PrepareProposalResponse]
	processProposal     *connect.Client[v1.ProcessProposalRequest, v1.ProcessProposalResponse]
	extendVote          *connect.Client[v1.ExtendVoteRequest, v1.ExtendVoteResponse]
	verifyVoteExtension *connect.Client[v1.VerifyVoteExtensionRequest, v1.VerifyVoteExtensionResponse]
	finalizeBlock       *connect.Client[v1.FinalizeBlockRequest, v1.FinalizeBlockResponse]
}

// Echo calls cometbft.abci.v1.ABCIService.Echo.
func (c *aBCIServiceClient) Echo(ctx context.Context, req *connect.Request[v1.EchoRequest]) (*connect.Response[v1.EchoResponse], error) {
	return c.echo.CallUnary(ctx, req)
}

// Flush calls cometbft.abci.v1.ABCIService.Flush.
func (c *aBCIServiceClient) Flush(ctx context.Context, req *connect.Request[v1.FlushRequest]) (*connect.Response[v1.FlushResponse], error) {
	return c.flush.CallUnary(ctx, req)
}

// Info calls cometbft.abci.v1.ABCIService.Info.
func (c *aBCIServiceClient) Info(ctx context.Context, req *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error) {
	return c.info.CallUnary(ctx, req)
}

// CheckTx calls cometbft.abci.v1.ABCIService.CheckTx.
func (c *aBCIServiceClient) CheckTx(ctx context.Context, req *connect.Request[v1.CheckTxRequest]) (*connect.Response[v1.CheckTxResponse], error) {
	return c.checkTx.CallUnary(ctx, req)
}

// Query calls cometbft.abci.v1.ABCIService.Query.
func (c *aBCIServiceClient) Query(ctx context.Context, req *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResponse], error) {
	return c.query.CallUnary(ctx, req)
}

// Commit calls cometbft.abci.v1.ABCIService.Commit.
func (c *aBCIServiceClient) Commit(ctx context.Context, req *connect.Request[v1.CommitRequest]) (*connect.Response[v1.CommitResponse], error) {
	return c.commit.CallUnary(ctx, req)
}

// InitChain calls cometbft.abci.v1.ABCIService.InitChain.
func (c *aBCIServiceClient) InitChain(ctx context.Context, req *connect.Request[v1.InitChainRequest]) (*connect.Response[v1.InitChainResponse], error) {
	return c.initChain.CallUnary(ctx, req)
}

// ListSnapshots calls cometbft.abci.v1.ABCIService.ListSnapshots.
func (c *aBCIServiceClient) ListSnapshots(ctx context.Context, req *connect.Request[v1.ListSnapshotsRequest]) (*connect.Response[v1.ListSnapshotsResponse], error) {
	return c.listSnapshots.CallUnary(ctx, req)
}

// OfferSnapshot calls cometbft.abci.v1.ABCIService.OfferSnapshot.
func (c *aBCIServiceClient) OfferSnapshot(ctx context.Context, req *connect.Request[v1.OfferSnapshotRequest]) (*connect.Response[v1.OfferSnapshotResponse], error) {
	return c.offerSnapshot.CallUnary(ctx, req)
}

// LoadSnapshotChunk calls cometbft.abci.v1.ABCIService.LoadSnapshotChunk.
func (c *aBCIServiceClient) LoadSnapshotChunk(ctx context.Context, req *connect.Request[v1.LoadSnapshotChunkRequest]) (*connect.Response[v1.LoadSnapshotChunkResponse], error) {
	return c.loadSnapshotChunk.CallUnary(ctx, req)
}

// ApplySnapshotChunk calls cometbft.abci.v1.ABCIService.ApplySnapshotChunk.
func (c *aBCIServiceClient) ApplySnapshotChunk(ctx context.Context, req *connect.Request[v1.ApplySnapshotChunkRequest]) (*connect.Response[v1.ApplySnapshotChunkResponse], error) {
	return c.applySnapshotChunk.CallUnary(ctx, req)
}

// PrepareProposal calls cometbft.abci.v1.ABCIService.PrepareProposal.
func (c *aBCIServiceClient) PrepareProposal(ctx context.Context, req *connect.Request[v1.PrepareProposalRequest]) (*connect.Response[v1.PrepareProposalResponse], error) {
	return c.prepareProposal.CallUnary(ctx, req)
}

// ProcessProposal calls cometbft.abci.v1.ABCIService.ProcessProposal.
func (c *aBCIServiceClient) ProcessProposal(ctx context.Context, req *connect.Request[v1.ProcessProposalRequest]) (*connect.Response[v1.ProcessProposalResponse], error) {
	return c.processProposal.CallUnary(ctx, req)
}

// ExtendVote calls cometbft.abci.v1.ABCIService.ExtendVote.
func (c *aBCIServiceClient) ExtendVote(ctx context.Context, req *connect.Request[v1.ExtendVoteRequest]) (*connect.Response[v1.ExtendVoteResponse], error) {
	return c.extendVote.CallUnary(ctx, req)
}

// VerifyVoteExtension calls cometbft.abci.v1.ABCIService.VerifyVoteExtension.
func (c *aBCIServiceClient) VerifyVoteExtension(ctx context.Context, req *connect.Request[v1.VerifyVoteExtensionRequest]) (*connect.Response[v1.VerifyVoteExtensionResponse], error) {
	return c.verifyVoteExtension.CallUnary(ctx, req)
}

// FinalizeBlock calls cometbft.abci.v1.ABCIService.FinalizeBlock.
func (c *aBCIServiceClient) FinalizeBlock(ctx context.Context, req *connect.Request[v1.FinalizeBlockRequest]) (*connect.Response[v1.FinalizeBlockResponse], error) {
	return c.finalizeBlock.CallUnary(ctx, req)
}

// ABCIServiceHandler is an implementation of the cometbft.abci.v1.ABCIService service.
type ABCIServiceHandler interface {
	// Echo returns back the same message it is sent.
	Echo(context.Context, *connect.Request[v1.EchoRequest]) (*connect.Response[v1.EchoResponse], error)
	// Flush flushes the write buffer.
	Flush(context.Context, *connect.Request[v1.FlushRequest]) (*connect.Response[v1.FlushResponse], error)
	// Info returns information about the application state.
	Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error)
	// CheckTx validates a transaction.
	CheckTx(context.Context, *connect.Request[v1.CheckTxRequest]) (*connect.Response[v1.CheckTxResponse], error)
	// Query queries the application state.
	Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResponse], error)
	// Commit commits a block of transactions.
	Commit(context.Context, *connect.Request[v1.CommitRequest]) (*connect.Response[v1.CommitResponse], error)
	// InitChain initializes the blockchain.
	InitChain(context.Context, *connect.Request[v1.InitChainRequest]) (*connect.Response[v1.InitChainResponse], error)
	// ListSnapshots lists all the available snapshots.
	ListSnapshots(context.Context, *connect.Request[v1.ListSnapshotsRequest]) (*connect.Response[v1.ListSnapshotsResponse], error)
	// OfferSnapshot sends a snapshot offer.
	OfferSnapshot(context.Context, *connect.Request[v1.OfferSnapshotRequest]) (*connect.Response[v1.OfferSnapshotResponse], error)
	// LoadSnapshotChunk returns a chunk of snapshot.
	LoadSnapshotChunk(context.Context, *connect.Request[v1.LoadSnapshotChunkRequest]) (*connect.Response[v1.LoadSnapshotChunkResponse], error)
	// ApplySnapshotChunk applies a chunk of snapshot.
	ApplySnapshotChunk(context.Context, *connect.Request[v1.ApplySnapshotChunkRequest]) (*connect.Response[v1.ApplySnapshotChunkResponse], error)
	// PrepareProposal returns a proposal for the next block.
	PrepareProposal(context.Context, *connect.Request[v1.PrepareProposalRequest]) (*connect.Response[v1.PrepareProposalResponse], error)
	// ProcessProposal validates a proposal.
	ProcessProposal(context.Context, *connect.Request[v1.ProcessProposalRequest]) (*connect.Response[v1.ProcessProposalResponse], error)
	// ExtendVote extends a vote with application-injected data (vote extensions).
	ExtendVote(context.Context, *connect.Request[v1.ExtendVoteRequest]) (*connect.Response[v1.ExtendVoteResponse], error)
	// VerifyVoteExtension verifies a vote extension.
	VerifyVoteExtension(context.Context, *connect.Request[v1.VerifyVoteExtensionRequest]) (*connect.Response[v1.VerifyVoteExtensionResponse], error)
	// FinalizeBlock finalizes a block.
	FinalizeBlock(context.Context, *connect.Request[v1.FinalizeBlockRequest]) (*connect.Response[v1.FinalizeBlockResponse], error)
}

// NewABCIServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewABCIServiceHandler(svc ABCIServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	aBCIServiceEchoHandler := connect.NewUnaryHandler(
		ABCIServiceEchoProcedure,
		svc.Echo,
		connect.WithSchema(aBCIServiceEchoMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceFlushHandler := connect.NewUnaryHandler(
		ABCIServiceFlushProcedure,
		svc.Flush,
		connect.WithSchema(aBCIServiceFlushMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceInfoHandler := connect.NewUnaryHandler(
		ABCIServiceInfoProcedure,
		svc.Info,
		connect.WithSchema(aBCIServiceInfoMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceCheckTxHandler := connect.NewUnaryHandler(
		ABCIServiceCheckTxProcedure,
		svc.CheckTx,
		connect.WithSchema(aBCIServiceCheckTxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceQueryHandler := connect.NewUnaryHandler(
		ABCIServiceQueryProcedure,
		svc.Query,
		connect.WithSchema(aBCIServiceQueryMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceCommitHandler := connect.NewUnaryHandler(
		ABCIServiceCommitProcedure,
		svc.Commit,
		connect.WithSchema(aBCIServiceCommitMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceInitChainHandler := connect.NewUnaryHandler(
		ABCIServiceInitChainProcedure,
		svc.InitChain,
		connect.WithSchema(aBCIServiceInitChainMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceListSnapshotsHandler := connect.NewUnaryHandler(
		ABCIServiceListSnapshotsProcedure,
		svc.ListSnapshots,
		connect.WithSchema(aBCIServiceListSnapshotsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceOfferSnapshotHandler := connect.NewUnaryHandler(
		ABCIServiceOfferSnapshotProcedure,
		svc.OfferSnapshot,
		connect.WithSchema(aBCIServiceOfferSnapshotMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceLoadSnapshotChunkHandler := connect.NewUnaryHandler(
		ABCIServiceLoadSnapshotChunkProcedure,
		svc.LoadSnapshotChunk,
		connect.WithSchema(aBCIServiceLoadSnapshotChunkMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceApplySnapshotChunkHandler := connect.NewUnaryHandler(
		ABCIServiceApplySnapshotChunkProcedure,
		svc.ApplySnapshotChunk,
		connect.WithSchema(aBCIServiceApplySnapshotChunkMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServicePrepareProposalHandler := connect.NewUnaryHandler(
		ABCIServicePrepareProposalProcedure,
		svc.PrepareProposal,
		connect.WithSchema(aBCIServicePrepareProposalMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceProcessProposalHandler := connect.NewUnaryHandler(
		ABCIServiceProcessProposalProcedure,
		svc.ProcessProposal,
		connect.WithSchema(aBCIServiceProcessProposalMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceExtendVoteHandler := connect.NewUnaryHandler(
		ABCIServiceExtendVoteProcedure,
		svc.ExtendVote,
		connect.WithSchema(aBCIServiceExtendVoteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceVerifyVoteExtensionHandler := connect.NewUnaryHandler(
		ABCIServiceVerifyVoteExtensionProcedure,
		svc.VerifyVoteExtension,
		connect.WithSchema(aBCIServiceVerifyVoteExtensionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIServiceFinalizeBlockHandler := connect.NewUnaryHandler(
		ABCIServiceFinalizeBlockProcedure,
		svc.FinalizeBlock,
		connect.WithSchema(aBCIServiceFinalizeBlockMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/cometbft.abci.v1.ABCIService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ABCIServiceEchoProcedure:
			aBCIServiceEchoHandler.ServeHTTP(w, r)
		case ABCIServiceFlushProcedure:
			aBCIServiceFlushHandler.ServeHTTP(w, r)
		case ABCIServiceInfoProcedure:
			aBCIServiceInfoHandler.ServeHTTP(w, r)
		case ABCIServiceCheckTxProcedure:
			aBCIServiceCheckTxHandler.ServeHTTP(w, r)
		case ABCIServiceQueryProcedure:
			aBCIServiceQueryHandler.ServeHTTP(w, r)
		case ABCIServiceCommitProcedure:
			aBCIServiceCommitHandler.ServeHTTP(w, r)
		case ABCIServiceInitChainProcedure:
			aBCIServiceInitChainHandler.ServeHTTP(w, r)
		case ABCIServiceListSnapshotsProcedure:
			aBCIServiceListSnapshotsHandler.ServeHTTP(w, r)
		case ABCIServiceOfferSnapshotProcedure:
			aBCIServiceOfferSnapshotHandler.ServeHTTP(w, r)
		case ABCIServiceLoadSnapshotChunkProcedure:
			aBCIServiceLoadSnapshotChunkHandler.ServeHTTP(w, r)
		case ABCIServiceApplySnapshotChunkProcedure:
			aBCIServiceApplySnapshotChunkHandler.ServeHTTP(w, r)
		case ABCIServicePrepareProposalProcedure:
			aBCIServicePrepareProposalHandler.ServeHTTP(w, r)
		case ABCIServiceProcessProposalProcedure:
			aBCIServiceProcessProposalHandler.ServeHTTP(w, r)
		case ABCIServiceExtendVoteProcedure:
			aBCIServiceExtendVoteHandler.ServeHTTP(w, r)
		case ABCIServiceVerifyVoteExtensionProcedure:
			aBCIServiceVerifyVoteExtensionHandler.ServeHTTP(w, r)
		case ABCIServiceFinalizeBlockProcedure:
			aBCIServiceFinalizeBlockHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedABCIServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedABCIServiceHandler struct{}

func (UnimplementedABCIServiceHandler) Echo(context.Context, *connect.Request[v1.EchoRequest]) (*connect.Response[v1.EchoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.Echo is not implemented"))
}

func (UnimplementedABCIServiceHandler) Flush(context.Context, *connect.Request[v1.FlushRequest]) (*connect.Response[v1.FlushResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.Flush is not implemented"))
}

func (UnimplementedABCIServiceHandler) Info(context.Context, *connect.Request[v1.InfoRequest]) (*connect.Response[v1.InfoResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.Info is not implemented"))
}

func (UnimplementedABCIServiceHandler) CheckTx(context.Context, *connect.Request[v1.CheckTxRequest]) (*connect.Response[v1.CheckTxResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.CheckTx is not implemented"))
}

func (UnimplementedABCIServiceHandler) Query(context.Context, *connect.Request[v1.QueryRequest]) (*connect.Response[v1.QueryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.Query is not implemented"))
}

func (UnimplementedABCIServiceHandler) Commit(context.Context, *connect.Request[v1.CommitRequest]) (*connect.Response[v1.CommitResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.Commit is not implemented"))
}

func (UnimplementedABCIServiceHandler) InitChain(context.Context, *connect.Request[v1.InitChainRequest]) (*connect.Response[v1.InitChainResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.InitChain is not implemented"))
}

func (UnimplementedABCIServiceHandler) ListSnapshots(context.Context, *connect.Request[v1.ListSnapshotsRequest]) (*connect.Response[v1.ListSnapshotsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.ListSnapshots is not implemented"))
}

func (UnimplementedABCIServiceHandler) OfferSnapshot(context.Context, *connect.Request[v1.OfferSnapshotRequest]) (*connect.Response[v1.OfferSnapshotResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.OfferSnapshot is not implemented"))
}

func (UnimplementedABCIServiceHandler) LoadSnapshotChunk(context.Context, *connect.Request[v1.LoadSnapshotChunkRequest]) (*connect.Response[v1.LoadSnapshotChunkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.LoadSnapshotChunk is not implemented"))
}

func (UnimplementedABCIServiceHandler) ApplySnapshotChunk(context.Context, *connect.Request[v1.ApplySnapshotChunkRequest]) (*connect.Response[v1.ApplySnapshotChunkResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.ApplySnapshotChunk is not implemented"))
}

func (UnimplementedABCIServiceHandler) PrepareProposal(context.Context, *connect.Request[v1.PrepareProposalRequest]) (*connect.Response[v1.PrepareProposalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.PrepareProposal is not implemented"))
}

func (UnimplementedABCIServiceHandler) ProcessProposal(context.Context, *connect.Request[v1.ProcessProposalRequest]) (*connect.Response[v1.ProcessProposalResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.ProcessProposal is not implemented"))
}

func (UnimplementedABCIServiceHandler) ExtendVote(context.Context, *connect.Request[v1.ExtendVoteRequest]) (*connect.Response[v1.ExtendVoteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.ExtendVote is not implemented"))
}

func (UnimplementedABCIServiceHandler) VerifyVoteExtension(context.Context, *connect.Request[v1.VerifyVoteExtensionRequest]) (*connect.Response[v1.VerifyVoteExtensionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.VerifyVoteExtension is not implemented"))
}

func (UnimplementedABCIServiceHandler) FinalizeBlock(context.Context, *connect.Request[v1.FinalizeBlockRequest]) (*connect.Response[v1.FinalizeBlockResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1.ABCIService.FinalizeBlock is not implemented"))
}
