// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gql

type Query struct {
}

type Track struct {
	ID          string  `json:"id"`
	Title       string  `json:"title"`
	StreamURL   *string `json:"streamUrl,omitempty"`
	Description *string `json:"description,omitempty"`
	User        *User   `json:"user"`
}

type User struct {
	ID     string  `json:"id"`
	Handle string  `json:"handle"`
	Bio    *string `json:"bio,omitempty"`
}
