// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: cometbft/services/pruning/v1/service.proto

package pruningv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PruningService_SetBlockRetainHeight_FullMethodName        = "/cometbft.services.pruning.v1.PruningService/SetBlockRetainHeight"
	PruningService_GetBlockRetainHeight_FullMethodName        = "/cometbft.services.pruning.v1.PruningService/GetBlockRetainHeight"
	PruningService_SetBlockResultsRetainHeight_FullMethodName = "/cometbft.services.pruning.v1.PruningService/SetBlockResultsRetainHeight"
	PruningService_GetBlockResultsRetainHeight_FullMethodName = "/cometbft.services.pruning.v1.PruningService/GetBlockResultsRetainHeight"
	PruningService_SetTxIndexerRetainHeight_FullMethodName    = "/cometbft.services.pruning.v1.PruningService/SetTxIndexerRetainHeight"
	PruningService_GetTxIndexerRetainHeight_FullMethodName    = "/cometbft.services.pruning.v1.PruningService/GetTxIndexerRetainHeight"
	PruningService_SetBlockIndexerRetainHeight_FullMethodName = "/cometbft.services.pruning.v1.PruningService/SetBlockIndexerRetainHeight"
	PruningService_GetBlockIndexerRetainHeight_FullMethodName = "/cometbft.services.pruning.v1.PruningService/GetBlockIndexerRetainHeight"
)

// PruningServiceClient is the client API for PruningService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PruningService provides privileged access to specialized pruning
// functionality on the CometBFT node to help control node storage.
type PruningServiceClient interface {
	// SetBlockRetainHeightRequest indicates to the node that it can safely
	// prune all block data up to the specified retain height.
	//
	// The lower of this retain height and that set by the application in its
	// Commit response will be used by the node to determine which heights' data
	// can be pruned.
	SetBlockRetainHeight(ctx context.Context, in *SetBlockRetainHeightRequest, opts ...grpc.CallOption) (*SetBlockRetainHeightResponse, error)
	// GetBlockRetainHeight returns information about the retain height
	// parameters used by the node to influence block retention/pruning.
	GetBlockRetainHeight(ctx context.Context, in *GetBlockRetainHeightRequest, opts ...grpc.CallOption) (*GetBlockRetainHeightResponse, error)
	// SetBlockResultsRetainHeightRequest indicates to the node that it can
	// safely prune all block results data up to the specified height.
	//
	// The node will always store the block results for the latest height to
	// help facilitate crash recovery.
	SetBlockResultsRetainHeight(ctx context.Context, in *SetBlockResultsRetainHeightRequest, opts ...grpc.CallOption) (*SetBlockResultsRetainHeightResponse, error)
	// GetBlockResultsRetainHeight returns information about the retain height
	// parameters used by the node to influence block results retention/pruning.
	GetBlockResultsRetainHeight(ctx context.Context, in *GetBlockResultsRetainHeightRequest, opts ...grpc.CallOption) (*GetBlockResultsRetainHeightResponse, error)
	// SetTxIndexerRetainHeightRequest indicates to the node that it can safely
	// prune all tx indices up to the specified retain height.
	SetTxIndexerRetainHeight(ctx context.Context, in *SetTxIndexerRetainHeightRequest, opts ...grpc.CallOption) (*SetTxIndexerRetainHeightResponse, error)
	// GetTxIndexerRetainHeight returns information about the retain height
	// parameters used by the node to influence TxIndexer pruning
	GetTxIndexerRetainHeight(ctx context.Context, in *GetTxIndexerRetainHeightRequest, opts ...grpc.CallOption) (*GetTxIndexerRetainHeightResponse, error)
	// SetBlockIndexerRetainHeightRequest indicates to the node that it can safely
	// prune all block indices up to the specified retain height.
	SetBlockIndexerRetainHeight(ctx context.Context, in *SetBlockIndexerRetainHeightRequest, opts ...grpc.CallOption) (*SetBlockIndexerRetainHeightResponse, error)
	// GetBlockIndexerRetainHeight returns information about the retain height
	// parameters used by the node to influence BlockIndexer pruning
	GetBlockIndexerRetainHeight(ctx context.Context, in *GetBlockIndexerRetainHeightRequest, opts ...grpc.CallOption) (*GetBlockIndexerRetainHeightResponse, error)
}

type pruningServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPruningServiceClient(cc grpc.ClientConnInterface) PruningServiceClient {
	return &pruningServiceClient{cc}
}

func (c *pruningServiceClient) SetBlockRetainHeight(ctx context.Context, in *SetBlockRetainHeightRequest, opts ...grpc.CallOption) (*SetBlockRetainHeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBlockRetainHeightResponse)
	err := c.cc.Invoke(ctx, PruningService_SetBlockRetainHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pruningServiceClient) GetBlockRetainHeight(ctx context.Context, in *GetBlockRetainHeightRequest, opts ...grpc.CallOption) (*GetBlockRetainHeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockRetainHeightResponse)
	err := c.cc.Invoke(ctx, PruningService_GetBlockRetainHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pruningServiceClient) SetBlockResultsRetainHeight(ctx context.Context, in *SetBlockResultsRetainHeightRequest, opts ...grpc.CallOption) (*SetBlockResultsRetainHeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBlockResultsRetainHeightResponse)
	err := c.cc.Invoke(ctx, PruningService_SetBlockResultsRetainHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pruningServiceClient) GetBlockResultsRetainHeight(ctx context.Context, in *GetBlockResultsRetainHeightRequest, opts ...grpc.CallOption) (*GetBlockResultsRetainHeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockResultsRetainHeightResponse)
	err := c.cc.Invoke(ctx, PruningService_GetBlockResultsRetainHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pruningServiceClient) SetTxIndexerRetainHeight(ctx context.Context, in *SetTxIndexerRetainHeightRequest, opts ...grpc.CallOption) (*SetTxIndexerRetainHeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetTxIndexerRetainHeightResponse)
	err := c.cc.Invoke(ctx, PruningService_SetTxIndexerRetainHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pruningServiceClient) GetTxIndexerRetainHeight(ctx context.Context, in *GetTxIndexerRetainHeightRequest, opts ...grpc.CallOption) (*GetTxIndexerRetainHeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTxIndexerRetainHeightResponse)
	err := c.cc.Invoke(ctx, PruningService_GetTxIndexerRetainHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pruningServiceClient) SetBlockIndexerRetainHeight(ctx context.Context, in *SetBlockIndexerRetainHeightRequest, opts ...grpc.CallOption) (*SetBlockIndexerRetainHeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBlockIndexerRetainHeightResponse)
	err := c.cc.Invoke(ctx, PruningService_SetBlockIndexerRetainHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pruningServiceClient) GetBlockIndexerRetainHeight(ctx context.Context, in *GetBlockIndexerRetainHeightRequest, opts ...grpc.CallOption) (*GetBlockIndexerRetainHeightResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlockIndexerRetainHeightResponse)
	err := c.cc.Invoke(ctx, PruningService_GetBlockIndexerRetainHeight_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PruningServiceServer is the server API for PruningService service.
// All implementations must embed UnimplementedPruningServiceServer
// for forward compatibility.
//
// PruningService provides privileged access to specialized pruning
// functionality on the CometBFT node to help control node storage.
type PruningServiceServer interface {
	// SetBlockRetainHeightRequest indicates to the node that it can safely
	// prune all block data up to the specified retain height.
	//
	// The lower of this retain height and that set by the application in its
	// Commit response will be used by the node to determine which heights' data
	// can be pruned.
	SetBlockRetainHeight(context.Context, *SetBlockRetainHeightRequest) (*SetBlockRetainHeightResponse, error)
	// GetBlockRetainHeight returns information about the retain height
	// parameters used by the node to influence block retention/pruning.
	GetBlockRetainHeight(context.Context, *GetBlockRetainHeightRequest) (*GetBlockRetainHeightResponse, error)
	// SetBlockResultsRetainHeightRequest indicates to the node that it can
	// safely prune all block results data up to the specified height.
	//
	// The node will always store the block results for the latest height to
	// help facilitate crash recovery.
	SetBlockResultsRetainHeight(context.Context, *SetBlockResultsRetainHeightRequest) (*SetBlockResultsRetainHeightResponse, error)
	// GetBlockResultsRetainHeight returns information about the retain height
	// parameters used by the node to influence block results retention/pruning.
	GetBlockResultsRetainHeight(context.Context, *GetBlockResultsRetainHeightRequest) (*GetBlockResultsRetainHeightResponse, error)
	// SetTxIndexerRetainHeightRequest indicates to the node that it can safely
	// prune all tx indices up to the specified retain height.
	SetTxIndexerRetainHeight(context.Context, *SetTxIndexerRetainHeightRequest) (*SetTxIndexerRetainHeightResponse, error)
	// GetTxIndexerRetainHeight returns information about the retain height
	// parameters used by the node to influence TxIndexer pruning
	GetTxIndexerRetainHeight(context.Context, *GetTxIndexerRetainHeightRequest) (*GetTxIndexerRetainHeightResponse, error)
	// SetBlockIndexerRetainHeightRequest indicates to the node that it can safely
	// prune all block indices up to the specified retain height.
	SetBlockIndexerRetainHeight(context.Context, *SetBlockIndexerRetainHeightRequest) (*SetBlockIndexerRetainHeightResponse, error)
	// GetBlockIndexerRetainHeight returns information about the retain height
	// parameters used by the node to influence BlockIndexer pruning
	GetBlockIndexerRetainHeight(context.Context, *GetBlockIndexerRetainHeightRequest) (*GetBlockIndexerRetainHeightResponse, error)
	mustEmbedUnimplementedPruningServiceServer()
}

// UnimplementedPruningServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPruningServiceServer struct{}

func (UnimplementedPruningServiceServer) SetBlockRetainHeight(context.Context, *SetBlockRetainHeightRequest) (*SetBlockRetainHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBlockRetainHeight not implemented")
}
func (UnimplementedPruningServiceServer) GetBlockRetainHeight(context.Context, *GetBlockRetainHeightRequest) (*GetBlockRetainHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockRetainHeight not implemented")
}
func (UnimplementedPruningServiceServer) SetBlockResultsRetainHeight(context.Context, *SetBlockResultsRetainHeightRequest) (*SetBlockResultsRetainHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBlockResultsRetainHeight not implemented")
}
func (UnimplementedPruningServiceServer) GetBlockResultsRetainHeight(context.Context, *GetBlockResultsRetainHeightRequest) (*GetBlockResultsRetainHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockResultsRetainHeight not implemented")
}
func (UnimplementedPruningServiceServer) SetTxIndexerRetainHeight(context.Context, *SetTxIndexerRetainHeightRequest) (*SetTxIndexerRetainHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetTxIndexerRetainHeight not implemented")
}
func (UnimplementedPruningServiceServer) GetTxIndexerRetainHeight(context.Context, *GetTxIndexerRetainHeightRequest) (*GetTxIndexerRetainHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTxIndexerRetainHeight not implemented")
}
func (UnimplementedPruningServiceServer) SetBlockIndexerRetainHeight(context.Context, *SetBlockIndexerRetainHeightRequest) (*SetBlockIndexerRetainHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBlockIndexerRetainHeight not implemented")
}
func (UnimplementedPruningServiceServer) GetBlockIndexerRetainHeight(context.Context, *GetBlockIndexerRetainHeightRequest) (*GetBlockIndexerRetainHeightResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBlockIndexerRetainHeight not implemented")
}
func (UnimplementedPruningServiceServer) mustEmbedUnimplementedPruningServiceServer() {}
func (UnimplementedPruningServiceServer) testEmbeddedByValue()                        {}

// UnsafePruningServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PruningServiceServer will
// result in compilation errors.
type UnsafePruningServiceServer interface {
	mustEmbedUnimplementedPruningServiceServer()
}

func RegisterPruningServiceServer(s grpc.ServiceRegistrar, srv PruningServiceServer) {
	// If the following call pancis, it indicates UnimplementedPruningServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PruningService_ServiceDesc, srv)
}

func _PruningService_SetBlockRetainHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBlockRetainHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PruningServiceServer).SetBlockRetainHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PruningService_SetBlockRetainHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PruningServiceServer).SetBlockRetainHeight(ctx, req.(*SetBlockRetainHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PruningService_GetBlockRetainHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockRetainHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PruningServiceServer).GetBlockRetainHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PruningService_GetBlockRetainHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PruningServiceServer).GetBlockRetainHeight(ctx, req.(*GetBlockRetainHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PruningService_SetBlockResultsRetainHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBlockResultsRetainHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PruningServiceServer).SetBlockResultsRetainHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PruningService_SetBlockResultsRetainHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PruningServiceServer).SetBlockResultsRetainHeight(ctx, req.(*SetBlockResultsRetainHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PruningService_GetBlockResultsRetainHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockResultsRetainHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PruningServiceServer).GetBlockResultsRetainHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PruningService_GetBlockResultsRetainHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PruningServiceServer).GetBlockResultsRetainHeight(ctx, req.(*GetBlockResultsRetainHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PruningService_SetTxIndexerRetainHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetTxIndexerRetainHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PruningServiceServer).SetTxIndexerRetainHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PruningService_SetTxIndexerRetainHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PruningServiceServer).SetTxIndexerRetainHeight(ctx, req.(*SetTxIndexerRetainHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PruningService_GetTxIndexerRetainHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTxIndexerRetainHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PruningServiceServer).GetTxIndexerRetainHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PruningService_GetTxIndexerRetainHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PruningServiceServer).GetTxIndexerRetainHeight(ctx, req.(*GetTxIndexerRetainHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PruningService_SetBlockIndexerRetainHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBlockIndexerRetainHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PruningServiceServer).SetBlockIndexerRetainHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PruningService_SetBlockIndexerRetainHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PruningServiceServer).SetBlockIndexerRetainHeight(ctx, req.(*SetBlockIndexerRetainHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PruningService_GetBlockIndexerRetainHeight_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlockIndexerRetainHeightRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PruningServiceServer).GetBlockIndexerRetainHeight(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PruningService_GetBlockIndexerRetainHeight_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PruningServiceServer).GetBlockIndexerRetainHeight(ctx, req.(*GetBlockIndexerRetainHeightRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PruningService_ServiceDesc is the grpc.ServiceDesc for PruningService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PruningService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cometbft.services.pruning.v1.PruningService",
	HandlerType: (*PruningServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetBlockRetainHeight",
			Handler:    _PruningService_SetBlockRetainHeight_Handler,
		},
		{
			MethodName: "GetBlockRetainHeight",
			Handler:    _PruningService_GetBlockRetainHeight_Handler,
		},
		{
			MethodName: "SetBlockResultsRetainHeight",
			Handler:    _PruningService_SetBlockResultsRetainHeight_Handler,
		},
		{
			MethodName: "GetBlockResultsRetainHeight",
			Handler:    _PruningService_GetBlockResultsRetainHeight_Handler,
		},
		{
			MethodName: "SetTxIndexerRetainHeight",
			Handler:    _PruningService_SetTxIndexerRetainHeight_Handler,
		},
		{
			MethodName: "GetTxIndexerRetainHeight",
			Handler:    _PruningService_GetTxIndexerRetainHeight_Handler,
		},
		{
			MethodName: "SetBlockIndexerRetainHeight",
			Handler:    _PruningService_SetBlockIndexerRetainHeight_Handler,
		},
		{
			MethodName: "GetBlockIndexerRetainHeight",
			Handler:    _PruningService_GetBlockIndexerRetainHeight_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cometbft/services/pruning/v1/service.proto",
}
