// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cometbft/services/block/v1/block_service.proto

package blockv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/alecsavvy/clockwise/api/cometbft/services/block/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BlockServiceName is the fully-qualified name of the BlockService service.
	BlockServiceName = "cometbft.services.block.v1.BlockService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BlockServiceGetByHeightProcedure is the fully-qualified name of the BlockService's GetByHeight
	// RPC.
	BlockServiceGetByHeightProcedure = "/cometbft.services.block.v1.BlockService/GetByHeight"
	// BlockServiceGetLatestHeightProcedure is the fully-qualified name of the BlockService's
	// GetLatestHeight RPC.
	BlockServiceGetLatestHeightProcedure = "/cometbft.services.block.v1.BlockService/GetLatestHeight"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	blockServiceServiceDescriptor               = v1.File_cometbft_services_block_v1_block_service_proto.Services().ByName("BlockService")
	blockServiceGetByHeightMethodDescriptor     = blockServiceServiceDescriptor.Methods().ByName("GetByHeight")
	blockServiceGetLatestHeightMethodDescriptor = blockServiceServiceDescriptor.Methods().ByName("GetLatestHeight")
)

// BlockServiceClient is a client for the cometbft.services.block.v1.BlockService service.
type BlockServiceClient interface {
	// GetBlock retrieves the block information at a particular height.
	GetByHeight(context.Context, *connect.Request[v1.GetByHeightRequest]) (*connect.Response[v1.GetByHeightResponse], error)
	// GetLatestHeight returns a stream of the latest block heights committed by
	// the network. This is a long-lived stream that is only terminated by the
	// server if an error occurs. The caller is expected to handle such
	// disconnections and automatically reconnect.
	GetLatestHeight(context.Context, *connect.Request[v1.GetLatestHeightRequest]) (*connect.ServerStreamForClient[v1.GetLatestHeightResponse], error)
}

// NewBlockServiceClient constructs a client for the cometbft.services.block.v1.BlockService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBlockServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BlockServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &blockServiceClient{
		getByHeight: connect.NewClient[v1.GetByHeightRequest, v1.GetByHeightResponse](
			httpClient,
			baseURL+BlockServiceGetByHeightProcedure,
			connect.WithSchema(blockServiceGetByHeightMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getLatestHeight: connect.NewClient[v1.GetLatestHeightRequest, v1.GetLatestHeightResponse](
			httpClient,
			baseURL+BlockServiceGetLatestHeightProcedure,
			connect.WithSchema(blockServiceGetLatestHeightMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// blockServiceClient implements BlockServiceClient.
type blockServiceClient struct {
	getByHeight     *connect.Client[v1.GetByHeightRequest, v1.GetByHeightResponse]
	getLatestHeight *connect.Client[v1.GetLatestHeightRequest, v1.GetLatestHeightResponse]
}

// GetByHeight calls cometbft.services.block.v1.BlockService.GetByHeight.
func (c *blockServiceClient) GetByHeight(ctx context.Context, req *connect.Request[v1.GetByHeightRequest]) (*connect.Response[v1.GetByHeightResponse], error) {
	return c.getByHeight.CallUnary(ctx, req)
}

// GetLatestHeight calls cometbft.services.block.v1.BlockService.GetLatestHeight.
func (c *blockServiceClient) GetLatestHeight(ctx context.Context, req *connect.Request[v1.GetLatestHeightRequest]) (*connect.ServerStreamForClient[v1.GetLatestHeightResponse], error) {
	return c.getLatestHeight.CallServerStream(ctx, req)
}

// BlockServiceHandler is an implementation of the cometbft.services.block.v1.BlockService service.
type BlockServiceHandler interface {
	// GetBlock retrieves the block information at a particular height.
	GetByHeight(context.Context, *connect.Request[v1.GetByHeightRequest]) (*connect.Response[v1.GetByHeightResponse], error)
	// GetLatestHeight returns a stream of the latest block heights committed by
	// the network. This is a long-lived stream that is only terminated by the
	// server if an error occurs. The caller is expected to handle such
	// disconnections and automatically reconnect.
	GetLatestHeight(context.Context, *connect.Request[v1.GetLatestHeightRequest], *connect.ServerStream[v1.GetLatestHeightResponse]) error
}

// NewBlockServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBlockServiceHandler(svc BlockServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	blockServiceGetByHeightHandler := connect.NewUnaryHandler(
		BlockServiceGetByHeightProcedure,
		svc.GetByHeight,
		connect.WithSchema(blockServiceGetByHeightMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	blockServiceGetLatestHeightHandler := connect.NewServerStreamHandler(
		BlockServiceGetLatestHeightProcedure,
		svc.GetLatestHeight,
		connect.WithSchema(blockServiceGetLatestHeightMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/cometbft.services.block.v1.BlockService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BlockServiceGetByHeightProcedure:
			blockServiceGetByHeightHandler.ServeHTTP(w, r)
		case BlockServiceGetLatestHeightProcedure:
			blockServiceGetLatestHeightHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBlockServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBlockServiceHandler struct{}

func (UnimplementedBlockServiceHandler) GetByHeight(context.Context, *connect.Request[v1.GetByHeightRequest]) (*connect.Response[v1.GetByHeightResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.services.block.v1.BlockService.GetByHeight is not implemented"))
}

func (UnimplementedBlockServiceHandler) GetLatestHeight(context.Context, *connect.Request[v1.GetLatestHeightRequest], *connect.ServerStream[v1.GetLatestHeightResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.services.block.v1.BlockService.GetLatestHeight is not implemented"))
}
