// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: cometbft/rpc/grpc/v1beta3/types.proto

package grpcv1beta3

import (
	context "context"
	v1beta1 "github.com/alecsavvy/clockwise/api/cometbft/rpc/grpc/v1beta1"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BroadcastAPI_Ping_FullMethodName        = "/cometbft.rpc.grpc.v1beta3.BroadcastAPI/Ping"
	BroadcastAPI_BroadcastTx_FullMethodName = "/cometbft.rpc.grpc.v1beta3.BroadcastAPI/BroadcastTx"
)

// BroadcastAPIClient is the client API for BroadcastAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BroadcastAPI is an API for broadcasting transactions.
//
// Deprecated: This API will be superseded by a more comprehensive gRPC-based
// broadcast API, and is scheduled for removal after v0.38.
type BroadcastAPIClient interface {
	// Ping the connection.
	Ping(ctx context.Context, in *v1beta1.RequestPing, opts ...grpc.CallOption) (*v1beta1.ResponsePing, error)
	// BroadcastTx broadcasts a transaction.
	BroadcastTx(ctx context.Context, in *v1beta1.RequestBroadcastTx, opts ...grpc.CallOption) (*ResponseBroadcastTx, error)
}

type broadcastAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewBroadcastAPIClient(cc grpc.ClientConnInterface) BroadcastAPIClient {
	return &broadcastAPIClient{cc}
}

func (c *broadcastAPIClient) Ping(ctx context.Context, in *v1beta1.RequestPing, opts ...grpc.CallOption) (*v1beta1.ResponsePing, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(v1beta1.ResponsePing)
	err := c.cc.Invoke(ctx, BroadcastAPI_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *broadcastAPIClient) BroadcastTx(ctx context.Context, in *v1beta1.RequestBroadcastTx, opts ...grpc.CallOption) (*ResponseBroadcastTx, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResponseBroadcastTx)
	err := c.cc.Invoke(ctx, BroadcastAPI_BroadcastTx_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BroadcastAPIServer is the server API for BroadcastAPI service.
// All implementations must embed UnimplementedBroadcastAPIServer
// for forward compatibility.
//
// BroadcastAPI is an API for broadcasting transactions.
//
// Deprecated: This API will be superseded by a more comprehensive gRPC-based
// broadcast API, and is scheduled for removal after v0.38.
type BroadcastAPIServer interface {
	// Ping the connection.
	Ping(context.Context, *v1beta1.RequestPing) (*v1beta1.ResponsePing, error)
	// BroadcastTx broadcasts a transaction.
	BroadcastTx(context.Context, *v1beta1.RequestBroadcastTx) (*ResponseBroadcastTx, error)
	mustEmbedUnimplementedBroadcastAPIServer()
}

// UnimplementedBroadcastAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBroadcastAPIServer struct{}

func (UnimplementedBroadcastAPIServer) Ping(context.Context, *v1beta1.RequestPing) (*v1beta1.ResponsePing, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBroadcastAPIServer) BroadcastTx(context.Context, *v1beta1.RequestBroadcastTx) (*ResponseBroadcastTx, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BroadcastTx not implemented")
}
func (UnimplementedBroadcastAPIServer) mustEmbedUnimplementedBroadcastAPIServer() {}
func (UnimplementedBroadcastAPIServer) testEmbeddedByValue()                      {}

// UnsafeBroadcastAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BroadcastAPIServer will
// result in compilation errors.
type UnsafeBroadcastAPIServer interface {
	mustEmbedUnimplementedBroadcastAPIServer()
}

func RegisterBroadcastAPIServer(s grpc.ServiceRegistrar, srv BroadcastAPIServer) {
	// If the following call pancis, it indicates UnimplementedBroadcastAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BroadcastAPI_ServiceDesc, srv)
}

func _BroadcastAPI_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1beta1.RequestPing)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BroadcastAPIServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BroadcastAPI_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BroadcastAPIServer).Ping(ctx, req.(*v1beta1.RequestPing))
	}
	return interceptor(ctx, in, info, handler)
}

func _BroadcastAPI_BroadcastTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(v1beta1.RequestBroadcastTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BroadcastAPIServer).BroadcastTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BroadcastAPI_BroadcastTx_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BroadcastAPIServer).BroadcastTx(ctx, req.(*v1beta1.RequestBroadcastTx))
	}
	return interceptor(ctx, in, info, handler)
}

// BroadcastAPI_ServiceDesc is the grpc.ServiceDesc for BroadcastAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BroadcastAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cometbft.rpc.grpc.v1beta3.BroadcastAPI",
	HandlerType: (*BroadcastAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _BroadcastAPI_Ping_Handler,
		},
		{
			MethodName: "BroadcastTx",
			Handler:    _BroadcastAPI_BroadcastTx_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cometbft/rpc/grpc/v1beta3/types.proto",
}
