NetworkID = "dev"
NetworkTransactionCeiling = 1000
NetworkBlockMineMaximumMS = 5000

NodeEndpoint = "localhost:8080"
NodeBootstrapPeers = ["localhost:8081", "localhost:8082"]
NodeType = "sealer"

DatabaseBlockPersistenceThreshold = 15000
DatabasePruningIntervalMS = 60000
