syntax = "proto3";

package chain.v1;

import "ddex/ern/v381/v381.proto";
import "ddex/ern/v383/v383.proto";
import "ddex/ern/v42/v42.proto";
import "ddex/ern/v43/v43.proto";
import "ddex/ern/v432/v432.proto";
import "ddex/pie/v10/v10.proto";
import "ddex/mead/v11/v11.proto";

message ElectronicReleaseNotification {
  oneof msg {
    ddex.ern.v381.NewReleaseMessage v381 = 1;
    ddex.ern.v383.NewReleaseMessage v383 = 2;
    ddex.ern.v42.NewReleaseMessage v42 = 3;
    ddex.ern.v43.NewReleaseMessage v43 = 4;
    ddex.ern.v432.NewReleaseMessage v432 = 5;
  }
}

message PartyIdentificationAndEnrichment {
  oneof msg {
    ddex.pie.v10.PieMessage v10 = 1;
  }
}

message MediaEnrichmentAndDescription {
  oneof msg {
    ddex.mead.v11.MeadMessage v11 = 1;
  }
}
