// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: cometbft/abci/v1beta3/types.proto

package abciv1beta3connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1beta1 "github.com/alecsavvy/clockwise/api/cometbft/abci/v1beta1"
	v1beta2 "github.com/alecsavvy/clockwise/api/cometbft/abci/v1beta2"
	v1beta3 "github.com/alecsavvy/clockwise/api/cometbft/abci/v1beta3"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ABCIName is the fully-qualified name of the ABCI service.
	ABCIName = "cometbft.abci.v1beta3.ABCI"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ABCIEchoProcedure is the fully-qualified name of the ABCI's Echo RPC.
	ABCIEchoProcedure = "/cometbft.abci.v1beta3.ABCI/Echo"
	// ABCIFlushProcedure is the fully-qualified name of the ABCI's Flush RPC.
	ABCIFlushProcedure = "/cometbft.abci.v1beta3.ABCI/Flush"
	// ABCIInfoProcedure is the fully-qualified name of the ABCI's Info RPC.
	ABCIInfoProcedure = "/cometbft.abci.v1beta3.ABCI/Info"
	// ABCICheckTxProcedure is the fully-qualified name of the ABCI's CheckTx RPC.
	ABCICheckTxProcedure = "/cometbft.abci.v1beta3.ABCI/CheckTx"
	// ABCIQueryProcedure is the fully-qualified name of the ABCI's Query RPC.
	ABCIQueryProcedure = "/cometbft.abci.v1beta3.ABCI/Query"
	// ABCICommitProcedure is the fully-qualified name of the ABCI's Commit RPC.
	ABCICommitProcedure = "/cometbft.abci.v1beta3.ABCI/Commit"
	// ABCIInitChainProcedure is the fully-qualified name of the ABCI's InitChain RPC.
	ABCIInitChainProcedure = "/cometbft.abci.v1beta3.ABCI/InitChain"
	// ABCIListSnapshotsProcedure is the fully-qualified name of the ABCI's ListSnapshots RPC.
	ABCIListSnapshotsProcedure = "/cometbft.abci.v1beta3.ABCI/ListSnapshots"
	// ABCIOfferSnapshotProcedure is the fully-qualified name of the ABCI's OfferSnapshot RPC.
	ABCIOfferSnapshotProcedure = "/cometbft.abci.v1beta3.ABCI/OfferSnapshot"
	// ABCILoadSnapshotChunkProcedure is the fully-qualified name of the ABCI's LoadSnapshotChunk RPC.
	ABCILoadSnapshotChunkProcedure = "/cometbft.abci.v1beta3.ABCI/LoadSnapshotChunk"
	// ABCIApplySnapshotChunkProcedure is the fully-qualified name of the ABCI's ApplySnapshotChunk RPC.
	ABCIApplySnapshotChunkProcedure = "/cometbft.abci.v1beta3.ABCI/ApplySnapshotChunk"
	// ABCIPrepareProposalProcedure is the fully-qualified name of the ABCI's PrepareProposal RPC.
	ABCIPrepareProposalProcedure = "/cometbft.abci.v1beta3.ABCI/PrepareProposal"
	// ABCIProcessProposalProcedure is the fully-qualified name of the ABCI's ProcessProposal RPC.
	ABCIProcessProposalProcedure = "/cometbft.abci.v1beta3.ABCI/ProcessProposal"
	// ABCIExtendVoteProcedure is the fully-qualified name of the ABCI's ExtendVote RPC.
	ABCIExtendVoteProcedure = "/cometbft.abci.v1beta3.ABCI/ExtendVote"
	// ABCIVerifyVoteExtensionProcedure is the fully-qualified name of the ABCI's VerifyVoteExtension
	// RPC.
	ABCIVerifyVoteExtensionProcedure = "/cometbft.abci.v1beta3.ABCI/VerifyVoteExtension"
	// ABCIFinalizeBlockProcedure is the fully-qualified name of the ABCI's FinalizeBlock RPC.
	ABCIFinalizeBlockProcedure = "/cometbft.abci.v1beta3.ABCI/FinalizeBlock"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	aBCIServiceDescriptor                   = v1beta3.File_cometbft_abci_v1beta3_types_proto.Services().ByName("ABCI")
	aBCIEchoMethodDescriptor                = aBCIServiceDescriptor.Methods().ByName("Echo")
	aBCIFlushMethodDescriptor               = aBCIServiceDescriptor.Methods().ByName("Flush")
	aBCIInfoMethodDescriptor                = aBCIServiceDescriptor.Methods().ByName("Info")
	aBCICheckTxMethodDescriptor             = aBCIServiceDescriptor.Methods().ByName("CheckTx")
	aBCIQueryMethodDescriptor               = aBCIServiceDescriptor.Methods().ByName("Query")
	aBCICommitMethodDescriptor              = aBCIServiceDescriptor.Methods().ByName("Commit")
	aBCIInitChainMethodDescriptor           = aBCIServiceDescriptor.Methods().ByName("InitChain")
	aBCIListSnapshotsMethodDescriptor       = aBCIServiceDescriptor.Methods().ByName("ListSnapshots")
	aBCIOfferSnapshotMethodDescriptor       = aBCIServiceDescriptor.Methods().ByName("OfferSnapshot")
	aBCILoadSnapshotChunkMethodDescriptor   = aBCIServiceDescriptor.Methods().ByName("LoadSnapshotChunk")
	aBCIApplySnapshotChunkMethodDescriptor  = aBCIServiceDescriptor.Methods().ByName("ApplySnapshotChunk")
	aBCIPrepareProposalMethodDescriptor     = aBCIServiceDescriptor.Methods().ByName("PrepareProposal")
	aBCIProcessProposalMethodDescriptor     = aBCIServiceDescriptor.Methods().ByName("ProcessProposal")
	aBCIExtendVoteMethodDescriptor          = aBCIServiceDescriptor.Methods().ByName("ExtendVote")
	aBCIVerifyVoteExtensionMethodDescriptor = aBCIServiceDescriptor.Methods().ByName("VerifyVoteExtension")
	aBCIFinalizeBlockMethodDescriptor       = aBCIServiceDescriptor.Methods().ByName("FinalizeBlock")
)

// ABCIClient is a client for the cometbft.abci.v1beta3.ABCI service.
type ABCIClient interface {
	// Echo returns back the same message it is sent.
	Echo(context.Context, *connect.Request[v1beta1.RequestEcho]) (*connect.Response[v1beta1.ResponseEcho], error)
	// Flush flushes the write buffer.
	Flush(context.Context, *connect.Request[v1beta1.RequestFlush]) (*connect.Response[v1beta1.ResponseFlush], error)
	// Info returns information about the application state.
	Info(context.Context, *connect.Request[v1beta2.RequestInfo]) (*connect.Response[v1beta1.ResponseInfo], error)
	// CheckTx validates a transaction.
	CheckTx(context.Context, *connect.Request[v1beta1.RequestCheckTx]) (*connect.Response[v1beta3.ResponseCheckTx], error)
	// Query queries the application state.
	Query(context.Context, *connect.Request[v1beta1.RequestQuery]) (*connect.Response[v1beta1.ResponseQuery], error)
	// Commit commits a block of transactions.
	Commit(context.Context, *connect.Request[v1beta1.RequestCommit]) (*connect.Response[v1beta3.ResponseCommit], error)
	// InitChain initializes the blockchain.
	InitChain(context.Context, *connect.Request[v1beta3.RequestInitChain]) (*connect.Response[v1beta3.ResponseInitChain], error)
	// ListSnapshots lists all the available snapshots.
	ListSnapshots(context.Context, *connect.Request[v1beta1.RequestListSnapshots]) (*connect.Response[v1beta1.ResponseListSnapshots], error)
	// OfferSnapshot sends a snapshot offer.
	OfferSnapshot(context.Context, *connect.Request[v1beta1.RequestOfferSnapshot]) (*connect.Response[v1beta1.ResponseOfferSnapshot], error)
	// LoadSnapshotChunk returns a chunk of snapshot.
	LoadSnapshotChunk(context.Context, *connect.Request[v1beta1.RequestLoadSnapshotChunk]) (*connect.Response[v1beta1.ResponseLoadSnapshotChunk], error)
	// ApplySnapshotChunk applies a chunk of snapshot.
	ApplySnapshotChunk(context.Context, *connect.Request[v1beta1.RequestApplySnapshotChunk]) (*connect.Response[v1beta1.ResponseApplySnapshotChunk], error)
	// PrepareProposal returns a proposal for the next block.
	PrepareProposal(context.Context, *connect.Request[v1beta3.RequestPrepareProposal]) (*connect.Response[v1beta2.ResponsePrepareProposal], error)
	// ProcessProposal validates a proposal.
	ProcessProposal(context.Context, *connect.Request[v1beta3.RequestProcessProposal]) (*connect.Response[v1beta2.ResponseProcessProposal], error)
	// ExtendVote extends a vote with application-injected data (vote extensions).
	ExtendVote(context.Context, *connect.Request[v1beta3.RequestExtendVote]) (*connect.Response[v1beta3.ResponseExtendVote], error)
	// VerifyVoteExtension verifies a vote extension.
	VerifyVoteExtension(context.Context, *connect.Request[v1beta3.RequestVerifyVoteExtension]) (*connect.Response[v1beta3.ResponseVerifyVoteExtension], error)
	// FinalizeBlock finalizes a block.
	FinalizeBlock(context.Context, *connect.Request[v1beta3.RequestFinalizeBlock]) (*connect.Response[v1beta3.ResponseFinalizeBlock], error)
}

// NewABCIClient constructs a client for the cometbft.abci.v1beta3.ABCI service. By default, it uses
// the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewABCIClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ABCIClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &aBCIClient{
		echo: connect.NewClient[v1beta1.RequestEcho, v1beta1.ResponseEcho](
			httpClient,
			baseURL+ABCIEchoProcedure,
			connect.WithSchema(aBCIEchoMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		flush: connect.NewClient[v1beta1.RequestFlush, v1beta1.ResponseFlush](
			httpClient,
			baseURL+ABCIFlushProcedure,
			connect.WithSchema(aBCIFlushMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		info: connect.NewClient[v1beta2.RequestInfo, v1beta1.ResponseInfo](
			httpClient,
			baseURL+ABCIInfoProcedure,
			connect.WithSchema(aBCIInfoMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		checkTx: connect.NewClient[v1beta1.RequestCheckTx, v1beta3.ResponseCheckTx](
			httpClient,
			baseURL+ABCICheckTxProcedure,
			connect.WithSchema(aBCICheckTxMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		query: connect.NewClient[v1beta1.RequestQuery, v1beta1.ResponseQuery](
			httpClient,
			baseURL+ABCIQueryProcedure,
			connect.WithSchema(aBCIQueryMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		commit: connect.NewClient[v1beta1.RequestCommit, v1beta3.ResponseCommit](
			httpClient,
			baseURL+ABCICommitProcedure,
			connect.WithSchema(aBCICommitMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		initChain: connect.NewClient[v1beta3.RequestInitChain, v1beta3.ResponseInitChain](
			httpClient,
			baseURL+ABCIInitChainProcedure,
			connect.WithSchema(aBCIInitChainMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		listSnapshots: connect.NewClient[v1beta1.RequestListSnapshots, v1beta1.ResponseListSnapshots](
			httpClient,
			baseURL+ABCIListSnapshotsProcedure,
			connect.WithSchema(aBCIListSnapshotsMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		offerSnapshot: connect.NewClient[v1beta1.RequestOfferSnapshot, v1beta1.ResponseOfferSnapshot](
			httpClient,
			baseURL+ABCIOfferSnapshotProcedure,
			connect.WithSchema(aBCIOfferSnapshotMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		loadSnapshotChunk: connect.NewClient[v1beta1.RequestLoadSnapshotChunk, v1beta1.ResponseLoadSnapshotChunk](
			httpClient,
			baseURL+ABCILoadSnapshotChunkProcedure,
			connect.WithSchema(aBCILoadSnapshotChunkMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		applySnapshotChunk: connect.NewClient[v1beta1.RequestApplySnapshotChunk, v1beta1.ResponseApplySnapshotChunk](
			httpClient,
			baseURL+ABCIApplySnapshotChunkProcedure,
			connect.WithSchema(aBCIApplySnapshotChunkMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		prepareProposal: connect.NewClient[v1beta3.RequestPrepareProposal, v1beta2.ResponsePrepareProposal](
			httpClient,
			baseURL+ABCIPrepareProposalProcedure,
			connect.WithSchema(aBCIPrepareProposalMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		processProposal: connect.NewClient[v1beta3.RequestProcessProposal, v1beta2.ResponseProcessProposal](
			httpClient,
			baseURL+ABCIProcessProposalProcedure,
			connect.WithSchema(aBCIProcessProposalMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		extendVote: connect.NewClient[v1beta3.RequestExtendVote, v1beta3.ResponseExtendVote](
			httpClient,
			baseURL+ABCIExtendVoteProcedure,
			connect.WithSchema(aBCIExtendVoteMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		verifyVoteExtension: connect.NewClient[v1beta3.RequestVerifyVoteExtension, v1beta3.ResponseVerifyVoteExtension](
			httpClient,
			baseURL+ABCIVerifyVoteExtensionProcedure,
			connect.WithSchema(aBCIVerifyVoteExtensionMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		finalizeBlock: connect.NewClient[v1beta3.RequestFinalizeBlock, v1beta3.ResponseFinalizeBlock](
			httpClient,
			baseURL+ABCIFinalizeBlockProcedure,
			connect.WithSchema(aBCIFinalizeBlockMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// aBCIClient implements ABCIClient.
type aBCIClient struct {
	echo                *connect.Client[v1beta1.RequestEcho, v1beta1.ResponseEcho]
	flush               *connect.Client[v1beta1.RequestFlush, v1beta1.ResponseFlush]
	info                *connect.Client[v1beta2.RequestInfo, v1beta1.ResponseInfo]
	checkTx             *connect.Client[v1beta1.RequestCheckTx, v1beta3.ResponseCheckTx]
	query               *connect.Client[v1beta1.RequestQuery, v1beta1.ResponseQuery]
	commit              *connect.Client[v1beta1.RequestCommit, v1beta3.ResponseCommit]
	initChain           *connect.Client[v1beta3.RequestInitChain, v1beta3.ResponseInitChain]
	listSnapshots       *connect.Client[v1beta1.RequestListSnapshots, v1beta1.ResponseListSnapshots]
	offerSnapshot       *connect.Client[v1beta1.RequestOfferSnapshot, v1beta1.ResponseOfferSnapshot]
	loadSnapshotChunk   *connect.Client[v1beta1.RequestLoadSnapshotChunk, v1beta1.ResponseLoadSnapshotChunk]
	applySnapshotChunk  *connect.Client[v1beta1.RequestApplySnapshotChunk, v1beta1.ResponseApplySnapshotChunk]
	prepareProposal     *connect.Client[v1beta3.RequestPrepareProposal, v1beta2.ResponsePrepareProposal]
	processProposal     *connect.Client[v1beta3.RequestProcessProposal, v1beta2.ResponseProcessProposal]
	extendVote          *connect.Client[v1beta3.RequestExtendVote, v1beta3.ResponseExtendVote]
	verifyVoteExtension *connect.Client[v1beta3.RequestVerifyVoteExtension, v1beta3.ResponseVerifyVoteExtension]
	finalizeBlock       *connect.Client[v1beta3.RequestFinalizeBlock, v1beta3.ResponseFinalizeBlock]
}

// Echo calls cometbft.abci.v1beta3.ABCI.Echo.
func (c *aBCIClient) Echo(ctx context.Context, req *connect.Request[v1beta1.RequestEcho]) (*connect.Response[v1beta1.ResponseEcho], error) {
	return c.echo.CallUnary(ctx, req)
}

// Flush calls cometbft.abci.v1beta3.ABCI.Flush.
func (c *aBCIClient) Flush(ctx context.Context, req *connect.Request[v1beta1.RequestFlush]) (*connect.Response[v1beta1.ResponseFlush], error) {
	return c.flush.CallUnary(ctx, req)
}

// Info calls cometbft.abci.v1beta3.ABCI.Info.
func (c *aBCIClient) Info(ctx context.Context, req *connect.Request[v1beta2.RequestInfo]) (*connect.Response[v1beta1.ResponseInfo], error) {
	return c.info.CallUnary(ctx, req)
}

// CheckTx calls cometbft.abci.v1beta3.ABCI.CheckTx.
func (c *aBCIClient) CheckTx(ctx context.Context, req *connect.Request[v1beta1.RequestCheckTx]) (*connect.Response[v1beta3.ResponseCheckTx], error) {
	return c.checkTx.CallUnary(ctx, req)
}

// Query calls cometbft.abci.v1beta3.ABCI.Query.
func (c *aBCIClient) Query(ctx context.Context, req *connect.Request[v1beta1.RequestQuery]) (*connect.Response[v1beta1.ResponseQuery], error) {
	return c.query.CallUnary(ctx, req)
}

// Commit calls cometbft.abci.v1beta3.ABCI.Commit.
func (c *aBCIClient) Commit(ctx context.Context, req *connect.Request[v1beta1.RequestCommit]) (*connect.Response[v1beta3.ResponseCommit], error) {
	return c.commit.CallUnary(ctx, req)
}

// InitChain calls cometbft.abci.v1beta3.ABCI.InitChain.
func (c *aBCIClient) InitChain(ctx context.Context, req *connect.Request[v1beta3.RequestInitChain]) (*connect.Response[v1beta3.ResponseInitChain], error) {
	return c.initChain.CallUnary(ctx, req)
}

// ListSnapshots calls cometbft.abci.v1beta3.ABCI.ListSnapshots.
func (c *aBCIClient) ListSnapshots(ctx context.Context, req *connect.Request[v1beta1.RequestListSnapshots]) (*connect.Response[v1beta1.ResponseListSnapshots], error) {
	return c.listSnapshots.CallUnary(ctx, req)
}

// OfferSnapshot calls cometbft.abci.v1beta3.ABCI.OfferSnapshot.
func (c *aBCIClient) OfferSnapshot(ctx context.Context, req *connect.Request[v1beta1.RequestOfferSnapshot]) (*connect.Response[v1beta1.ResponseOfferSnapshot], error) {
	return c.offerSnapshot.CallUnary(ctx, req)
}

// LoadSnapshotChunk calls cometbft.abci.v1beta3.ABCI.LoadSnapshotChunk.
func (c *aBCIClient) LoadSnapshotChunk(ctx context.Context, req *connect.Request[v1beta1.RequestLoadSnapshotChunk]) (*connect.Response[v1beta1.ResponseLoadSnapshotChunk], error) {
	return c.loadSnapshotChunk.CallUnary(ctx, req)
}

// ApplySnapshotChunk calls cometbft.abci.v1beta3.ABCI.ApplySnapshotChunk.
func (c *aBCIClient) ApplySnapshotChunk(ctx context.Context, req *connect.Request[v1beta1.RequestApplySnapshotChunk]) (*connect.Response[v1beta1.ResponseApplySnapshotChunk], error) {
	return c.applySnapshotChunk.CallUnary(ctx, req)
}

// PrepareProposal calls cometbft.abci.v1beta3.ABCI.PrepareProposal.
func (c *aBCIClient) PrepareProposal(ctx context.Context, req *connect.Request[v1beta3.RequestPrepareProposal]) (*connect.Response[v1beta2.ResponsePrepareProposal], error) {
	return c.prepareProposal.CallUnary(ctx, req)
}

// ProcessProposal calls cometbft.abci.v1beta3.ABCI.ProcessProposal.
func (c *aBCIClient) ProcessProposal(ctx context.Context, req *connect.Request[v1beta3.RequestProcessProposal]) (*connect.Response[v1beta2.ResponseProcessProposal], error) {
	return c.processProposal.CallUnary(ctx, req)
}

// ExtendVote calls cometbft.abci.v1beta3.ABCI.ExtendVote.
func (c *aBCIClient) ExtendVote(ctx context.Context, req *connect.Request[v1beta3.RequestExtendVote]) (*connect.Response[v1beta3.ResponseExtendVote], error) {
	return c.extendVote.CallUnary(ctx, req)
}

// VerifyVoteExtension calls cometbft.abci.v1beta3.ABCI.VerifyVoteExtension.
func (c *aBCIClient) VerifyVoteExtension(ctx context.Context, req *connect.Request[v1beta3.RequestVerifyVoteExtension]) (*connect.Response[v1beta3.ResponseVerifyVoteExtension], error) {
	return c.verifyVoteExtension.CallUnary(ctx, req)
}

// FinalizeBlock calls cometbft.abci.v1beta3.ABCI.FinalizeBlock.
func (c *aBCIClient) FinalizeBlock(ctx context.Context, req *connect.Request[v1beta3.RequestFinalizeBlock]) (*connect.Response[v1beta3.ResponseFinalizeBlock], error) {
	return c.finalizeBlock.CallUnary(ctx, req)
}

// ABCIHandler is an implementation of the cometbft.abci.v1beta3.ABCI service.
type ABCIHandler interface {
	// Echo returns back the same message it is sent.
	Echo(context.Context, *connect.Request[v1beta1.RequestEcho]) (*connect.Response[v1beta1.ResponseEcho], error)
	// Flush flushes the write buffer.
	Flush(context.Context, *connect.Request[v1beta1.RequestFlush]) (*connect.Response[v1beta1.ResponseFlush], error)
	// Info returns information about the application state.
	Info(context.Context, *connect.Request[v1beta2.RequestInfo]) (*connect.Response[v1beta1.ResponseInfo], error)
	// CheckTx validates a transaction.
	CheckTx(context.Context, *connect.Request[v1beta1.RequestCheckTx]) (*connect.Response[v1beta3.ResponseCheckTx], error)
	// Query queries the application state.
	Query(context.Context, *connect.Request[v1beta1.RequestQuery]) (*connect.Response[v1beta1.ResponseQuery], error)
	// Commit commits a block of transactions.
	Commit(context.Context, *connect.Request[v1beta1.RequestCommit]) (*connect.Response[v1beta3.ResponseCommit], error)
	// InitChain initializes the blockchain.
	InitChain(context.Context, *connect.Request[v1beta3.RequestInitChain]) (*connect.Response[v1beta3.ResponseInitChain], error)
	// ListSnapshots lists all the available snapshots.
	ListSnapshots(context.Context, *connect.Request[v1beta1.RequestListSnapshots]) (*connect.Response[v1beta1.ResponseListSnapshots], error)
	// OfferSnapshot sends a snapshot offer.
	OfferSnapshot(context.Context, *connect.Request[v1beta1.RequestOfferSnapshot]) (*connect.Response[v1beta1.ResponseOfferSnapshot], error)
	// LoadSnapshotChunk returns a chunk of snapshot.
	LoadSnapshotChunk(context.Context, *connect.Request[v1beta1.RequestLoadSnapshotChunk]) (*connect.Response[v1beta1.ResponseLoadSnapshotChunk], error)
	// ApplySnapshotChunk applies a chunk of snapshot.
	ApplySnapshotChunk(context.Context, *connect.Request[v1beta1.RequestApplySnapshotChunk]) (*connect.Response[v1beta1.ResponseApplySnapshotChunk], error)
	// PrepareProposal returns a proposal for the next block.
	PrepareProposal(context.Context, *connect.Request[v1beta3.RequestPrepareProposal]) (*connect.Response[v1beta2.ResponsePrepareProposal], error)
	// ProcessProposal validates a proposal.
	ProcessProposal(context.Context, *connect.Request[v1beta3.RequestProcessProposal]) (*connect.Response[v1beta2.ResponseProcessProposal], error)
	// ExtendVote extends a vote with application-injected data (vote extensions).
	ExtendVote(context.Context, *connect.Request[v1beta3.RequestExtendVote]) (*connect.Response[v1beta3.ResponseExtendVote], error)
	// VerifyVoteExtension verifies a vote extension.
	VerifyVoteExtension(context.Context, *connect.Request[v1beta3.RequestVerifyVoteExtension]) (*connect.Response[v1beta3.ResponseVerifyVoteExtension], error)
	// FinalizeBlock finalizes a block.
	FinalizeBlock(context.Context, *connect.Request[v1beta3.RequestFinalizeBlock]) (*connect.Response[v1beta3.ResponseFinalizeBlock], error)
}

// NewABCIHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewABCIHandler(svc ABCIHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	aBCIEchoHandler := connect.NewUnaryHandler(
		ABCIEchoProcedure,
		svc.Echo,
		connect.WithSchema(aBCIEchoMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIFlushHandler := connect.NewUnaryHandler(
		ABCIFlushProcedure,
		svc.Flush,
		connect.WithSchema(aBCIFlushMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIInfoHandler := connect.NewUnaryHandler(
		ABCIInfoProcedure,
		svc.Info,
		connect.WithSchema(aBCIInfoMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCICheckTxHandler := connect.NewUnaryHandler(
		ABCICheckTxProcedure,
		svc.CheckTx,
		connect.WithSchema(aBCICheckTxMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIQueryHandler := connect.NewUnaryHandler(
		ABCIQueryProcedure,
		svc.Query,
		connect.WithSchema(aBCIQueryMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCICommitHandler := connect.NewUnaryHandler(
		ABCICommitProcedure,
		svc.Commit,
		connect.WithSchema(aBCICommitMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIInitChainHandler := connect.NewUnaryHandler(
		ABCIInitChainProcedure,
		svc.InitChain,
		connect.WithSchema(aBCIInitChainMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIListSnapshotsHandler := connect.NewUnaryHandler(
		ABCIListSnapshotsProcedure,
		svc.ListSnapshots,
		connect.WithSchema(aBCIListSnapshotsMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIOfferSnapshotHandler := connect.NewUnaryHandler(
		ABCIOfferSnapshotProcedure,
		svc.OfferSnapshot,
		connect.WithSchema(aBCIOfferSnapshotMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCILoadSnapshotChunkHandler := connect.NewUnaryHandler(
		ABCILoadSnapshotChunkProcedure,
		svc.LoadSnapshotChunk,
		connect.WithSchema(aBCILoadSnapshotChunkMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIApplySnapshotChunkHandler := connect.NewUnaryHandler(
		ABCIApplySnapshotChunkProcedure,
		svc.ApplySnapshotChunk,
		connect.WithSchema(aBCIApplySnapshotChunkMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIPrepareProposalHandler := connect.NewUnaryHandler(
		ABCIPrepareProposalProcedure,
		svc.PrepareProposal,
		connect.WithSchema(aBCIPrepareProposalMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIProcessProposalHandler := connect.NewUnaryHandler(
		ABCIProcessProposalProcedure,
		svc.ProcessProposal,
		connect.WithSchema(aBCIProcessProposalMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIExtendVoteHandler := connect.NewUnaryHandler(
		ABCIExtendVoteProcedure,
		svc.ExtendVote,
		connect.WithSchema(aBCIExtendVoteMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIVerifyVoteExtensionHandler := connect.NewUnaryHandler(
		ABCIVerifyVoteExtensionProcedure,
		svc.VerifyVoteExtension,
		connect.WithSchema(aBCIVerifyVoteExtensionMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	aBCIFinalizeBlockHandler := connect.NewUnaryHandler(
		ABCIFinalizeBlockProcedure,
		svc.FinalizeBlock,
		connect.WithSchema(aBCIFinalizeBlockMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/cometbft.abci.v1beta3.ABCI/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ABCIEchoProcedure:
			aBCIEchoHandler.ServeHTTP(w, r)
		case ABCIFlushProcedure:
			aBCIFlushHandler.ServeHTTP(w, r)
		case ABCIInfoProcedure:
			aBCIInfoHandler.ServeHTTP(w, r)
		case ABCICheckTxProcedure:
			aBCICheckTxHandler.ServeHTTP(w, r)
		case ABCIQueryProcedure:
			aBCIQueryHandler.ServeHTTP(w, r)
		case ABCICommitProcedure:
			aBCICommitHandler.ServeHTTP(w, r)
		case ABCIInitChainProcedure:
			aBCIInitChainHandler.ServeHTTP(w, r)
		case ABCIListSnapshotsProcedure:
			aBCIListSnapshotsHandler.ServeHTTP(w, r)
		case ABCIOfferSnapshotProcedure:
			aBCIOfferSnapshotHandler.ServeHTTP(w, r)
		case ABCILoadSnapshotChunkProcedure:
			aBCILoadSnapshotChunkHandler.ServeHTTP(w, r)
		case ABCIApplySnapshotChunkProcedure:
			aBCIApplySnapshotChunkHandler.ServeHTTP(w, r)
		case ABCIPrepareProposalProcedure:
			aBCIPrepareProposalHandler.ServeHTTP(w, r)
		case ABCIProcessProposalProcedure:
			aBCIProcessProposalHandler.ServeHTTP(w, r)
		case ABCIExtendVoteProcedure:
			aBCIExtendVoteHandler.ServeHTTP(w, r)
		case ABCIVerifyVoteExtensionProcedure:
			aBCIVerifyVoteExtensionHandler.ServeHTTP(w, r)
		case ABCIFinalizeBlockProcedure:
			aBCIFinalizeBlockHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedABCIHandler returns CodeUnimplemented from all methods.
type UnimplementedABCIHandler struct{}

func (UnimplementedABCIHandler) Echo(context.Context, *connect.Request[v1beta1.RequestEcho]) (*connect.Response[v1beta1.ResponseEcho], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.Echo is not implemented"))
}

func (UnimplementedABCIHandler) Flush(context.Context, *connect.Request[v1beta1.RequestFlush]) (*connect.Response[v1beta1.ResponseFlush], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.Flush is not implemented"))
}

func (UnimplementedABCIHandler) Info(context.Context, *connect.Request[v1beta2.RequestInfo]) (*connect.Response[v1beta1.ResponseInfo], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.Info is not implemented"))
}

func (UnimplementedABCIHandler) CheckTx(context.Context, *connect.Request[v1beta1.RequestCheckTx]) (*connect.Response[v1beta3.ResponseCheckTx], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.CheckTx is not implemented"))
}

func (UnimplementedABCIHandler) Query(context.Context, *connect.Request[v1beta1.RequestQuery]) (*connect.Response[v1beta1.ResponseQuery], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.Query is not implemented"))
}

func (UnimplementedABCIHandler) Commit(context.Context, *connect.Request[v1beta1.RequestCommit]) (*connect.Response[v1beta3.ResponseCommit], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.Commit is not implemented"))
}

func (UnimplementedABCIHandler) InitChain(context.Context, *connect.Request[v1beta3.RequestInitChain]) (*connect.Response[v1beta3.ResponseInitChain], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.InitChain is not implemented"))
}

func (UnimplementedABCIHandler) ListSnapshots(context.Context, *connect.Request[v1beta1.RequestListSnapshots]) (*connect.Response[v1beta1.ResponseListSnapshots], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.ListSnapshots is not implemented"))
}

func (UnimplementedABCIHandler) OfferSnapshot(context.Context, *connect.Request[v1beta1.RequestOfferSnapshot]) (*connect.Response[v1beta1.ResponseOfferSnapshot], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.OfferSnapshot is not implemented"))
}

func (UnimplementedABCIHandler) LoadSnapshotChunk(context.Context, *connect.Request[v1beta1.RequestLoadSnapshotChunk]) (*connect.Response[v1beta1.ResponseLoadSnapshotChunk], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.LoadSnapshotChunk is not implemented"))
}

func (UnimplementedABCIHandler) ApplySnapshotChunk(context.Context, *connect.Request[v1beta1.RequestApplySnapshotChunk]) (*connect.Response[v1beta1.ResponseApplySnapshotChunk], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.ApplySnapshotChunk is not implemented"))
}

func (UnimplementedABCIHandler) PrepareProposal(context.Context, *connect.Request[v1beta3.RequestPrepareProposal]) (*connect.Response[v1beta2.ResponsePrepareProposal], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.PrepareProposal is not implemented"))
}

func (UnimplementedABCIHandler) ProcessProposal(context.Context, *connect.Request[v1beta3.RequestProcessProposal]) (*connect.Response[v1beta2.ResponseProcessProposal], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.ProcessProposal is not implemented"))
}

func (UnimplementedABCIHandler) ExtendVote(context.Context, *connect.Request[v1beta3.RequestExtendVote]) (*connect.Response[v1beta3.ResponseExtendVote], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.ExtendVote is not implemented"))
}

func (UnimplementedABCIHandler) VerifyVoteExtension(context.Context, *connect.Request[v1beta3.RequestVerifyVoteExtension]) (*connect.Response[v1beta3.ResponseVerifyVoteExtension], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.VerifyVoteExtension is not implemented"))
}

func (UnimplementedABCIHandler) FinalizeBlock(context.Context, *connect.Request[v1beta3.RequestFinalizeBlock]) (*connect.Response[v1beta3.ResponseFinalizeBlock], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("cometbft.abci.v1beta3.ABCI.FinalizeBlock is not implemented"))
}
